//! @generated by `froglight-generator` #ecfea09

#[cfg(not(feature = "hashbrown"))]
use std::collections::HashMap;

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;
#[cfg(feature = "hashbrown")]
use hashbrown::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, FrogReadWrite)]
pub struct AdvancementUpdatePacket {
    pub field_0: bool,
    pub field_1: CompactString,
    pub field_2: Vec<()>,
    pub field_3: CompactString,
    pub field_4: CompactString,
    pub field_5: i64,
    pub field_6: Option<()>,
    pub field_7: HashMap<(), ()>,
    pub field_8: HashMap<(), ()>,
}
