//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct BlockEventPacket {
    pub field_0: BlockPosition,
    pub field_1: u8,
    pub field_2: u8,
}
