//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct BlockEntityUpdatePacket {
    pub field_0: BlockPosition,
    pub field_1: Nbt,
}
