//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;
use simdnbt::owned::Nbt;

use crate::common::BlockPosition;

#[derive(Debug, Clone, PartialEq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct BlockEntityUpdatePacket {
    pub field_0: BlockPosition,
    pub field_1: Nbt,
}
