//! @generated by `froglight-generator` #ecfea09

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deref, DerefMut, From, Into, FrogReadWrite)]
pub struct BlockUpdatePacket {
    pub field_0: BlockPosition,
}
