//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct BlockEventPacket {
    pub field_0: BlockPosition,
    pub field_1: u8,
    pub field_2: u8,
}
