//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ChangeUnlockedRecipesPacket {
    pub field_0: Enum,
    pub field_1: bool,
    pub field_2: bool,
    pub field_3: CompactString,
    pub field_4: Vec<()>,
    pub field_5: CompactString,
    pub field_6: Vec<()>,
}
