//! @generated by `froglight-generator` #3ae6f0f

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct ChangeUnlockedRecipesPacket {
    pub field_0: Enum,
    pub field_1: bool,
    pub field_2: bool,
    pub field_3: CompactString,
    pub field_4: Vec<()>,
    pub field_5: CompactString,
    pub field_6: Vec<()>,
}
