//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ChatSuggestionsPacket {
    pub field_0: Enum,
    pub field_1: CompactString,
    pub field_2: Vec<()>,
}
