//! @generated by `froglight-generator` #73eaa37

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct ChatCommandSignedPacket {
    pub field_0: CompactString,
    pub field_1: i64,
    pub field_2: i64,
    pub field_3: CompactString,
    pub field_4: [u8],
    pub field_5: Vec<()>,
    #[frog(var)]
    pub field_6: u32,
    pub field_7: FixedBitSet,
}
