//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ChatMessagePacket {
    pub field_0: CompactString,
    pub field_1: i64,
    pub field_2: i64,
    pub field_3: [u8],
    pub field_4: Option<()>,
    #[frog(var)]
    pub field_5: u32,
    pub field_6: FixedBitSet,
}
