//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ChunkDeltaUpdatePacket {
    pub field_0: i64,
    #[frog(var)]
    pub field_1: u32,
    #[frog(var)]
    pub field_2: u64,
}
