//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ChunkBiomeDataPacket {
    pub field_0: ChunkPos,
    pub field_1: Vec<u8>,
    pub field_2: Vec<()>,
}
