//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ClientCommandPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: Enum,
    #[frog(var)]
    pub field_2: u32,
}
