//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct CommandTreePacket {
    pub field_0: u8,
    pub field_1: Vec<i32>,
    #[frog(var)]
    pub field_2: u32,
    pub field_3: CompactString,
    #[frog(var)]
    pub field_4: u32,
    pub field_5: ResourceKey,
    pub field_6: CompactString,
    pub field_7: Vec<()>,
    #[frog(var)]
    pub field_8: u32,
}
