//! @generated by `froglight-generator` #ecfea09

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Deref, DerefMut, From, Into, FrogReadWrite)]
pub struct CookieRequestPacket {
    pub field_0: ResourceKey,
}
