//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct CreativeInventoryActionPacket {
    pub field_0: i16,
    pub field_1: Option<()>,
}
