//! @generated by `froglight-generator` #ecfea09

#[cfg(not(feature = "hashbrown"))]
use std::collections::HashMap;

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;
#[cfg(feature = "hashbrown")]
use hashbrown::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, Deref, DerefMut, From, Into, FrogReadWrite)]
pub struct CustomReportDetailsPacket {
    pub field_0: HashMap<(), ()>,
}
