//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct DebugSamplePacket {
    pub field_0: Vec<i64>,
    pub field_1: Enum,
}
