//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct EntityPassengersSetPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: Vec<i32>,
}
