//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct EntityRotateAndMoveRelativePacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: i16,
    pub field_2: i16,
    pub field_3: i16,
    pub field_4: u8,
    pub field_5: u8,
    pub field_6: bool,
}
