//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct EntityDamagePacket {
    #[frog(var)]
    pub field_0: u32,
    #[frog(var)]
    pub field_1: u32,
    #[frog(var)]
    pub field_2: u32,
    pub field_3: f64,
    pub field_4: f64,
    pub field_5: f64,
    pub field_6: Option<()>,
}
