//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, FrogReadWrite)]
pub struct ExplosionPacket {
    pub field_0: f64,
    pub field_1: f64,
    pub field_2: f64,
    pub field_3: f32,
    pub field_4: u8,
    pub field_5: u8,
    pub field_6: u8,
    pub field_7: Vec<()>,
    pub field_8: f32,
    pub field_9: f32,
    pub field_10: f32,
    pub field_11: Enum,
}
