//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::{BlockPosition, ResourceKey};

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct GameJoinPacket {
    pub field_0: i32,
    pub field_1: bool,
    pub field_2: ResourceKey,
    pub field_3: Vec<()>,
    #[frog(var)]
    pub field_4: u32,
    #[frog(var)]
    pub field_5: u32,
    #[frog(var)]
    pub field_6: u32,
    pub field_7: bool,
    pub field_8: bool,
    pub field_9: bool,
    pub field_10: ResourceKey,
    pub field_11: i64,
    pub field_12: u8,
    pub field_13: u8,
    pub field_14: bool,
    pub field_15: bool,
    pub field_16: ResourceKey,
    pub field_17: BlockPosition,
    pub field_18: Option<()>,
    #[frog(var)]
    pub field_19: u32,
    pub field_20: bool,
}
