//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct InventoryPacket {
    pub field_0: u8,
    #[frog(var)]
    pub field_1: u32,
}
