//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct JigsawGeneratingPacket {
    pub field_0: BlockPosition,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: bool,
}
