//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct JigsawGeneratingPacket {
    pub field_0: BlockPosition,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: bool,
}
