//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct LightUpdatePacket {
    #[frog(var)]
    pub field_0: u32,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: BitSet,
    pub field_3: BitSet,
    pub field_4: BitSet,
    pub field_5: BitSet,
    pub field_6: Vec<()>,
    pub field_7: Vec<()>,
}
