//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct LightUpdatePacket {
    #[frog(var)]
    pub field_0: u32,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: BitSet,
    pub field_3: BitSet,
    pub field_4: BitSet,
    pub field_5: BitSet,
    pub field_6: Vec<()>,
    pub field_7: Vec<()>,
}
