//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct PlayerSpawnPositionPacket {
    pub field_0: BlockPosition,
    pub field_1: f32,
}
