//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct PlayerListPacket {
    pub field_0: BitSet,
    pub field_1: Uuid,
    pub field_2: Vec<()>,
}
