//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct PlayerInputPacket {
    pub field_0: f32,
    pub field_1: f32,
    pub field_2: u8,
}
