//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct PlayerListPacket {
    pub field_0: BitSet,
    pub field_1: Uuid,
    pub field_2: Vec<()>,
}
