//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct PlayerPositionLookPacket {
    pub field_0: f64,
    pub field_1: f64,
    pub field_2: f64,
    pub field_3: f32,
    pub field_4: f32,
    pub field_5: u8,
    #[frog(var)]
    pub field_6: u32,
}
