//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct PlayerSessionPacket {
    pub field_0: Uuid,
    pub field_1: i64,
    pub field_2: PublicKey,
    pub field_3: Vec<u8>,
}
