//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct PlayerInteractBlockPacket {
    pub field_0: Enum,
    pub field_1: BlockHitResult,
    #[frog(var)]
    pub field_2: u32,
}
