//! @generated by `froglight-generator` #73eaa37

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct PlaySoundFromEntityPacket {
    pub field_0: Enum,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: f32,
    pub field_3: f32,
    pub field_4: i64,
}
