//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct PlayerInteractItemPacket {
    pub field_0: Enum,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: f32,
    pub field_3: f32,
}
