//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct QueryBlockNbtPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: BlockPosition,
}
