//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct RecipeCategoryOptionsPacket {
    pub field_0: Enum,
    pub field_1: bool,
    pub field_2: bool,
}
