//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ScoreboardObjectiveUpdatePacket {
    pub field_0: CompactString,
    pub field_1: u8,
    pub field_2: Enum,
}
