//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ScoreboardDisplayPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: CompactString,
}
