//! @generated by `froglight-generator` #3ae6f0f

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct ScoreboardObjectiveUpdatePacket {
    pub field_0: CompactString,
    pub field_1: u8,
    pub field_2: Enum,
}
