//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ScoreboardScoreUpdatePacket {
    pub field_0: CompactString,
    pub field_1: CompactString,
    #[frog(var)]
    pub field_2: u32,
    pub field_3: Option<Text>,
    pub field_4: Option<()>,
}
