//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ServerMetadataPacket {
    pub field_0: Text,
    pub field_1: Vec<u8>,
}
