//! @generated by `froglight-generator` #ecfea09

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct ServerTransferPacket {
    pub field_0: CompactString,
    #[frog(var)]
    pub field_1: u32,
}
