//! @generated by `froglight-generator` #3ae6f0f

#[cfg(not(feature = "hashbrown"))]
use std::collections::HashMap;

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;
#[cfg(feature = "hashbrown")]
use hashbrown::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, Deref, DerefMut, From, Into, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct StatisticsPacket {
    pub field_0: HashMap<(), ()>,
}
