//! @generated by `froglight-generator` #3ae6f0f

#[cfg(not(feature = "hashbrown"))]
use std::collections::HashMap;

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;
#[cfg(feature = "hashbrown")]
use hashbrown::HashMap;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct SynchronizeTagsPacket {
    pub field_0: ResourceKey,
    pub field_1: CompactString,
    #[frog(var)]
    pub field_2: u32,
    #[frog(var)]
    pub field_3: u32,
    pub field_4: HashMap<(), ()>,
    pub field_5: HashMap<(), ()>,
}
