//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct TitleFadePacket {
    pub field_0: i32,
    pub field_1: i32,
    pub field_2: i32,
}
