//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct WorldEventPacket {
    pub field_0: i32,
    pub field_1: BlockPosition,
    pub field_2: i32,
    pub field_3: bool,
}
