//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct WorldTimeUpdatePacket {
    pub field_0: i64,
    pub field_1: i64,
}
