//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
pub struct WorldBorderCenterChangedPacket {
    pub field_0: f64,
    pub field_1: f64,
}
