//! @generated by `froglight-generator` #3ae6f0f

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct WorldBorderInterpolateSizePacket {
    pub field_0: f64,
    pub field_1: f64,
    #[frog(var)]
    pub field_2: u64,
}
