//! @generated by `froglight-generator` #cff0bd9

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct WorldTimeUpdatePacket;
