//! [`Status`](crate::states::Status) state packets for
//! [`V1_20_3`](super::V1_20_3)
//!
//! @generated by `froglight-generator #a28591a`
#![allow(missing_docs)]

use froglight_macros::frog_state;

pub use crate::versions::v1_20_2::status::*;

frog_state! {
    Status,
    V1_20_3,
    Clientbound {
        0u32 => QueryResponseS2CPacket,
        1u32 => PingResultS2CPacket,
    },
    Serverbound {
        0u32 => QueryRequestC2SPacket,
        1u32 => QueryPingC2SPacket,
    },
}
