//! Packets for [`Status`](crate::state::Status)
//!
//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}
#![expect(missing_docs)]

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use derive_more::{From, TryInto, TryUnwrap};

pub use crate::v1_21_4::play::{PingResultS2CPacket, QueryPingC2SPacket};

mod c2s_0x00_status_request;
pub use c2s_0x00_status_request::QueryRequestC2SPacket;

mod s2c_0x00_status_response;
pub use s2c_0x00_status_response::QueryResponseS2CPacket;

#[repr(u8)]
#[derive(Debug, Clone, PartialEq, From, TryInto, TryUnwrap)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogPackets))]
pub enum ClientboundStatusPackets {
    QueryResponse(QueryResponseS2CPacket) = 0x00,
    PingResult(PingResultS2CPacket) = 0x01,
}

#[repr(u8)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, From, TryInto, TryUnwrap)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogPackets))]
pub enum ServerboundStatusPackets {
    QueryRequest(QueryRequestC2SPacket) = 0x00,
    QueryPing(QueryPingC2SPacket) = 0x01,
}
