//! All blocks and block data
//!
//! @generated by `froglight-generator #dc73c64`

use bevy_app::App;

pub mod attributes;
#[allow(clippy::module_inception)]
pub mod blocks;

#[cfg(feature = "inspector")]
mod reflect;

mod registry;
pub use registry::BlockRegistry;

mod traits;
pub use traits::BlockType;

mod versions;
pub use versions::{
    BlockV1_20_0, BlockV1_20_2, BlockV1_20_3, ReflectBlockV1_20_0, ReflectBlockV1_20_2,
    ReflectBlockV1_20_3,
};

#[doc(hidden)]
pub(super) fn build(app: &mut App) { registry::build(app); }
