// @generated by froglight-generator 2b81467

/// All possible blocks in the game
///
/// ---
///
/// ### Warning
/// Because this enum is version independent,
/// not all blocks may be available in all versions.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Blocks {
    /// Air Block
    #[default]
    Air,
}
