//! All blocks and block data
// @generated by froglight-generator 2b81467

use bevy_app::App;
use bevy_reflect::Reflect;

#[doc(hidden)]
pub(super) fn build(app: &mut App) { app.register_type::<Blocks>(); }

/// All possible blocks in the game
///
/// ---
///
/// ### Warning
/// Because this enum is version independent,
/// not all blocks may be available in all versions.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Reflect)]
pub enum Blocks {
    /// Air Block
    #[default]
    Air,
}
