//! [`Handshaking`] state packets for [`1.20.0`]
//!
//! @generated by `froglight-generator #00f1b4b`
#![allow(missing_docs)]

use froglight_macros::frog_state;

mod handshakec2spacket;
pub use handshakec2spacket::*;

frog_state! {
    Handshaking,
    V1_20_0,
    Serverbound {
        0x00 => HandshakeC2SPacket,
    },
}
