//! Generated registries for
//! [`V1_21_0`](froglight_protocol::versions::v1_21_0::V1_21_0).
//!
//! @generated by `froglight-generator #NULL`

mod blocks;
mod registries;

#[doc(hidden)]
pub(super) fn build(app: &mut bevy_app::App) { registries::build(app); }
