//! Generated registries for [`V1_21_0`]
//!
//! @generated by `froglight-generator` #3701f00

use froglight_protocol::versions::v1_21_0::V1_21_0;

use crate::definitions::BlockRegistry;

mod blocks;
mod registries;

#[doc(hidden)]
pub(super) fn build(app: &mut bevy_app::App) { app.init_resource::<BlockRegistry<V1_21_0>>(); }
