//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_world::prelude::BlockPos;

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct JigsawGeneratingC2SPacket {
    pub position: BlockPos,
    #[cfg_attr(feature = "io", frog(var))]
    pub max_depth: u32,
    pub keep_jigsaws: bool,
}
