//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

use crate::common::UnsizedVec;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf), frog(version))]
pub struct ClickSlotC2SPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub container_id: u32,
    #[cfg_attr(feature = "io", frog(var))]
    pub state_id: u32,
    pub slot: u16,
    pub button: u8,
    pub unknown: UnsizedVec<u8>,
}
