//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

use bevy_platform::prelude::Vec;
#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use smol_str::SmolStr;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct BookUpdateC2SPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub slot_id: u32,
    pub pages: Vec<SmolStr>,
    pub title: Option<SmolStr>,
}
