//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "std")]
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use derive_more::{Deref, DerefMut, From, Into};

#[repr(transparent)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Deref, DerefMut, From, Into)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct QueryPingC2SPacket {
    pub timestamp: u64,
}

#[cfg(feature = "std")]
impl QueryPingC2SPacket {
    /// Create a new [`QueryPingC2SPacket`] with the current time in
    /// milliseconds since the [`UNIX_EPOCH`].
    #[must_use]
    #[allow(clippy::cast_possible_truncation, clippy::missing_panics_doc)]
    pub fn unix_epoch() -> Self {
        Self::from(SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis() as u64)
    }
}
