//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct SlotChangedStateC2SPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub slot_id: u32,
    #[cfg_attr(feature = "io", frog(var))]
    pub screen_handler_id: u32,
    pub new_state: bool,
}
