//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct CraftRequestC2SPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub container_id: u32,
    #[cfg_attr(feature = "io", frog(var))]
    pub recipe_id: u32,
    pub craft_all: bool,
}
