//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_common::entity::EntityId;

use crate::common::PlayerInteraction;

#[derive(Debug, Copy, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct PlayerInteractEntityC2SPacket {
    pub entity_id: EntityId,
    pub interaction: PlayerInteraction,
    pub sneaking: bool,
}
