//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use smol_str::SmolStr;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct UpdateStructureBlockC2SPacket {
    pub pos: (),
    pub action: (),
    pub mode: (),
    pub template_name: SmolStr,
    pub offset: i8,
    pub size: i8,
    pub mirror: (),
    pub rotation: (),
    pub metadata: SmolStr,
    pub integrity: f32,
    #[cfg_attr(feature = "io", frog(var))]
    pub seed: u64,
    pub show_bounding_box: i8,
}
