//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct ClickSlotC2SPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub sync_id: u32,
    #[cfg_attr(feature = "io", frog(var))]
    pub revision: u32,
    pub slot: u16,
    pub button: i8,
    pub action_type: (),
}
