//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_common::entity::EntityId;
use glam::{DVec3, U16Vec3};
use uuid::Uuid;

#[derive(Debug, Copy, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct EntitySpawnS2CPacket {
    pub entity_id: EntityId,
    pub uuid: Uuid,
    pub position: DVec3,
    pub pitch: i8,
    pub yaw: i8,
    pub head_yaw: i8,
    #[cfg_attr(feature = "io", frog(var))]
    pub entity_data: u32,
    pub velocity: U16Vec3,
}
