//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use smol_str::SmolStr;
use uuid::Uuid;

use crate::common::UnsizedBuffer;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct ResourcePackSendS2CPacket {
    pub uuid: Uuid,
    pub url: SmolStr,
    pub hash: SmolStr,
    pub required: bool,
    pub prompt: UnsizedBuffer<[u8; 16]>,
}
