//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

use bevy_platform::prelude::Vec;
#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct EntityPassengersSetS2CPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub entity_id: u32,
    pub passenger_ids: Vec<u32>,
}
