//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct EntitySpawnS2CPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub entity_id: u32,
    pub uuid: (),
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub pitch: i8,
    pub yaw: i8,
    pub head_yaw: i8,
    #[cfg_attr(feature = "io", frog(var))]
    pub entity_data: u32,
    pub velocity_x: u16,
    pub velocity_y: u16,
    pub velocity_z: u16,
}
