//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct PlaySoundS2CPacket {
    pub category: (),
    pub fixed_x: u32,
    pub fixed_y: u32,
    pub fixed_z: u32,
    pub volume: f32,
    pub pitch: f32,
    pub seed: u64,
}
