[package]
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
name = "froglight-facet-iter"
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

# --- Dependencies ---

[dependencies]
facet = { features = ["alloc", "reflect", "smallvec"], workspace = true }
facet-path = { features = ["alloc"], workspace = true }
facet-solver = { features = ["alloc"], workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
parking_lot = { workspace = true }
replace_with = { workspace = true }
smallvec = { features = ["const_generics", "const_new", "union"], workspace = true }

# Optional dependencies
ariadne = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
once_cell = { features = ["alloc", "parking_lot"], workspace = true, optional = true }

# --- Features ---

[features]
default = ["std"]

# Enable support for error reports.
report = ["dep:ariadne", "std"]

# Enable `tracing` support.
tracing = ["dep:tracing"]
# Enable extended `tracing` support.
tracing_ext = ["tracing"]

# Enable `once_cell` for `no_std` support.
once_cell = ["dep:once_cell"]

# Enable support for the standard library
std = ["facet/std", "facet-path/std", "facet-solver/std", "once_cell?/std", "replace_with/std", "tracing?/std"]
# Enable optimizations using the nightly toolchain
nightly = ["foldhash/nightly", "hashbrown/nightly", "parking_lot/nightly", "replace_with/nightly", "smallvec/specialization"]
