//! Packets for [`Login`](crate::state::Login)
//!
//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}
#![expect(missing_docs)]

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use derive_more::{From, TryUnwrap};

pub use crate::v1_21_4::login::{
    CookieRequestS2CPacket, CookieResponseC2SPacket, EnterConfigurationC2SPacket,
    LoginCompressionS2CPacket, LoginHelloC2SPacket, LoginHelloS2CPacket, LoginKeyC2SPacket,
    LoginQueryRequestS2CPacket, LoginQueryResponseC2SPacket, LoginSuccessS2CPacket,
};

mod s2c_0x00_login_disconnect;
pub use s2c_0x00_login_disconnect::LoginDisconnectS2CPacket;

#[repr(u8)]
#[derive(Debug, Clone, PartialEq, From, TryUnwrap)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogPackets))]
pub enum ClientboundLoginPackets {
    LoginDisconnect(LoginDisconnectS2CPacket) = 0x00,
    LoginHello(LoginHelloS2CPacket) = 0x01,
    LoginSuccess(LoginSuccessS2CPacket) = 0x02,
    LoginCompression(LoginCompressionS2CPacket) = 0x03,
    LoginQueryRequest(LoginQueryRequestS2CPacket) = 0x04,
    CookieRequest(CookieRequestS2CPacket) = 0x05,
}

#[repr(u8)]
#[derive(Debug, Clone, PartialEq, From, TryUnwrap)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogPackets))]
pub enum ServerboundLoginPackets {
    LoginHello(LoginHelloC2SPacket) = 0x00,
    LoginKey(LoginKeyC2SPacket) = 0x01,
    LoginQueryResponse(LoginQueryResponseC2SPacket) = 0x02,
    EnterConfiguration(EnterConfigurationC2SPacket) = 0x03,
    CookieResponse(CookieResponseC2SPacket) = 0x04,
}
