//! Protocol 765
//!
//! Used by Minecraft 1.20.3 - 1.20.4
//!
//! @generated by `froglight-generator #0ff4b67`

use crate::traits::Version;

pub mod configuration;
pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;

/// Protocol 765
///
/// Used by Minecraft 1.20.3 - 1.20.4
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "reflect", derive(bevy_reflect::Reflect))]
pub struct V1_20_3;

impl Version for V1_20_3 {
    const PROTOCOL_VERSION: i32 = 765i32;
}
