//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct CookieResponsePacket {
    pub field_0: ResourceKey,
    pub field_1: Option<()>,
}
