//! All biomes and biome data
//!
//! @generated by `froglight-generator #dc73c64`

use bevy_app::App;

pub mod biome_list;
use biome_list::BiomeEnum;

mod traits;
pub use traits::{BiomeExt, BiomeType};

mod reflect;
pub use reflect::ReflectBiomeType;

pub(crate) mod registry;
pub use registry::{BiomeRegistry, InnerBiomeRegistry};

#[doc(hidden)]
pub(super) fn build(app: &mut App) {
    // Register all biomes for reflection
    BiomeEnum::register(app);

    // Build and register the biome registry
    registry::build(app);
}
