//! All biomes and biome data
//!
//! @generated by `froglight-generator #dc73c64`

use bevy_app::App;
use bevy_reflect::Reflect;

#[doc(hidden)]
pub(super) fn build(app: &mut App) { app.register_type::<Biomes>(); }

/// All possible biomes in the game
///
/// ---
///
/// ### Warning
/// Because this enum is version independent,
/// not all biomes may be available in all versions.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Reflect)]
pub enum Biomes {
    /// The Plains biome
    #[default]
    Plains,
}
