//! @generated by `froglight-generator` #e606248

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct ClientCommandPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: Enum,
    #[frog(var)]
    pub field_2: u32,
}
