//! @generated by `froglight-generator` #e606248

use compact_str::CompactString;
use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Deref, DerefMut, From, Into, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct CommandExecutionPacket {
    pub field_0: CompactString,
}
