//! @generated by `froglight-generator` #e606248

use froglight_macros::FrogReadWrite;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct CookieResponsePacket {
    pub field_0: ResourceKey,
    pub field_1: Option<()>,
}
