//! [`Play`](crate::states::Play) state packets for
//! [`V1_21_2`](super::V1_21_2)
//!
//! @generated by `froglight-generator` #e606248
#![allow(missing_docs)]

mod bundle_delimiter;
pub use bundle_delimiter::*;

mod entity_spawn;
pub use entity_spawn::*;

mod experience_orb_spawn;
pub use experience_orb_spawn::*;

mod entity_animation;
pub use entity_animation::*;

mod statistics;
pub use statistics::*;

mod player_action_response;
pub use player_action_response::*;

mod block_breaking_progress;
pub use block_breaking_progress::*;

mod block_entity_update;
pub use block_entity_update::*;

mod block_event;
pub use block_event::*;

mod block_update;
pub use block_update::*;

mod boss_bar;
pub use boss_bar::*;

mod difficulty;
pub use difficulty::*;

mod chunk_sent;
pub use chunk_sent::*;

mod start_chunk_send;
pub use start_chunk_send::*;

mod chunk_biome_data;
pub use chunk_biome_data::*;

mod clear_title;
pub use clear_title::*;

mod command_suggestions;
pub use command_suggestions::*;

mod command_tree;
pub use command_tree::*;

mod close_screen;
pub use close_screen::*;

mod inventory;
pub use inventory::*;

mod screen_handler_property_update;
pub use screen_handler_property_update::*;

mod screen_handler_slot_update;
pub use screen_handler_slot_update::*;

mod cookie_request;
pub use cookie_request::*;

mod cooldown_update;
pub use cooldown_update::*;

mod chat_suggestions;
pub use chat_suggestions::*;

mod custom_payload_s2c;
pub use custom_payload_s2c::*;

mod entity_damage;
pub use entity_damage::*;

mod debug_sample;
pub use debug_sample::*;

mod remove_message;
pub use remove_message::*;

mod disconnect;
pub use disconnect::*;

mod profileless_chat_message;
pub use profileless_chat_message::*;

mod entity_status;
pub use entity_status::*;

mod entity_position_sync;
pub use entity_position_sync::*;

mod explosion;
pub use explosion::*;

mod unload_chunk;
pub use unload_chunk::*;

mod game_state_change;
pub use game_state_change::*;

mod open_horse_screen;
pub use open_horse_screen::*;

mod damage_tilt;
pub use damage_tilt::*;

mod world_border_initialize;
pub use world_border_initialize::*;

mod keep_alive_s2c;
pub use keep_alive_s2c::*;

mod chunk_data;
pub use chunk_data::*;

mod world_event;
pub use world_event::*;

mod particle;
pub use particle::*;

mod light_update;
pub use light_update::*;

mod game_join;
pub use game_join::*;

mod map_update;
pub use map_update::*;

mod set_trade_offers;
pub use set_trade_offers::*;

mod entity_move_relative;
pub use entity_move_relative::*;

mod entity_rotate_and_move_relative;
pub use entity_rotate_and_move_relative::*;

mod move_minecart_along_track;
pub use move_minecart_along_track::*;

mod entity_rotate;
pub use entity_rotate::*;

mod vehicle_move_s2c;
pub use vehicle_move_s2c::*;

mod open_written_book;
pub use open_written_book::*;

mod open_screen;
pub use open_screen::*;

mod sign_editor_open;
pub use sign_editor_open::*;

mod common_ping;
pub use common_ping::*;

mod ping_result;
pub use ping_result::*;

mod craft_failed_response;
pub use craft_failed_response::*;

mod player_abilities;
pub use player_abilities::*;

mod chat_message_s2c;
pub use chat_message_s2c::*;

mod end_combat;
pub use end_combat::*;

mod enter_combat;
pub use enter_combat::*;

mod death_message;
pub use death_message::*;

mod player_remove;
pub use player_remove::*;

mod player_list;
pub use player_list::*;

mod look_at;
pub use look_at::*;

mod player_position_look;
pub use player_position_look::*;

mod player_rotation_s_2_c_paket;
pub use player_rotation_s_2_c_paket::*;

mod recipe_book_add;
pub use recipe_book_add::*;

mod recipe_book_remove;
pub use recipe_book_remove::*;

mod recipe_book_settings;
pub use recipe_book_settings::*;

mod entities_destroy;
pub use entities_destroy::*;

mod remove_entity_status_effect;
pub use remove_entity_status_effect::*;

mod scoreboard_score_reset;
pub use scoreboard_score_reset::*;

mod resource_pack_remove;
pub use resource_pack_remove::*;

mod resource_pack_send;
pub use resource_pack_send::*;

mod player_respawn;
pub use player_respawn::*;

mod entity_set_head_yaw;
pub use entity_set_head_yaw::*;

mod chunk_delta_update;
pub use chunk_delta_update::*;

mod select_advancement_tab;
pub use select_advancement_tab::*;

mod server_metadata;
pub use server_metadata::*;

mod overlay_message;
pub use overlay_message::*;

mod world_border_center_changed;
pub use world_border_center_changed::*;

mod world_border_interpolate_size;
pub use world_border_interpolate_size::*;

mod world_border_size_changed;
pub use world_border_size_changed::*;

mod world_border_warning_time_changed;
pub use world_border_warning_time_changed::*;

mod world_border_warning_blocks_changed;
pub use world_border_warning_blocks_changed::*;

mod set_camera_entity;
pub use set_camera_entity::*;

mod chunk_render_distance_center;
pub use chunk_render_distance_center::*;

mod chunk_load_distance;
pub use chunk_load_distance::*;

mod set_cursor_item;
pub use set_cursor_item::*;

mod player_spawn_position;
pub use player_spawn_position::*;

mod scoreboard_display;
pub use scoreboard_display::*;

mod entity_tracker_update;
pub use entity_tracker_update::*;

mod entity_attach;
pub use entity_attach::*;

mod entity_velocity_update;
pub use entity_velocity_update::*;

mod entity_equipment_update;
pub use entity_equipment_update::*;

mod experience_bar_update;
pub use experience_bar_update::*;

mod health_update;
pub use health_update::*;

mod update_selected_slot_s2c;
pub use update_selected_slot_s2c::*;

mod scoreboard_objective_update;
pub use scoreboard_objective_update::*;

mod entity_passengers_set;
pub use entity_passengers_set::*;

mod set_player_inventory;
pub use set_player_inventory::*;

mod team;
pub use team::*;

mod scoreboard_score_update;
pub use scoreboard_score_update::*;

mod simulation_distance;
pub use simulation_distance::*;

mod subtitle;
pub use subtitle::*;

mod world_time_update;
pub use world_time_update::*;

mod title;
pub use title::*;

mod title_fade;
pub use title_fade::*;

mod play_sound_from_entity;
pub use play_sound_from_entity::*;

mod play_sound;
pub use play_sound::*;

mod enter_reconfiguration;
pub use enter_reconfiguration::*;

mod stop_sound;
pub use stop_sound::*;

mod store_cookie;
pub use store_cookie::*;

mod game_message;
pub use game_message::*;

mod player_list_header;
pub use player_list_header::*;

mod nbt_query_response;
pub use nbt_query_response::*;

mod item_pickup_animation;
pub use item_pickup_animation::*;

mod entity_position;
pub use entity_position::*;

mod update_tick_rate;
pub use update_tick_rate::*;

mod tick_step;
pub use tick_step::*;

mod server_transfer;
pub use server_transfer::*;

mod advancement_update;
pub use advancement_update::*;

mod entity_attributes;
pub use entity_attributes::*;

mod entity_status_effect;
pub use entity_status_effect::*;

mod synchronize_recipes;
pub use synchronize_recipes::*;

mod synchronize_tags;
pub use synchronize_tags::*;

mod projectile_power;
pub use projectile_power::*;

mod custom_report_details;
pub use custom_report_details::*;

mod server_links;
pub use server_links::*;

mod teleport_confirm;
pub use teleport_confirm::*;

mod query_block_nbt;
pub use query_block_nbt::*;

mod bundle_item_selected;
pub use bundle_item_selected::*;

mod update_difficulty;
pub use update_difficulty::*;

mod message_acknowledgment;
pub use message_acknowledgment::*;

mod command_execution;
pub use command_execution::*;

mod chat_command_signed;
pub use chat_command_signed::*;

mod chat_message_c2s;
pub use chat_message_c2s::*;

mod player_session;
pub use player_session::*;

mod acknowledge_chunks;
pub use acknowledge_chunks::*;

mod client_status;
pub use client_status::*;

mod client_tick_end;
pub use client_tick_end::*;

mod client_options;
pub use client_options::*;

mod request_command_completions;
pub use request_command_completions::*;

mod acknowledge_reconfiguration;
pub use acknowledge_reconfiguration::*;

mod button_click;
pub use button_click::*;

mod click_slot;
pub use click_slot::*;

mod close_handled_screen;
pub use close_handled_screen::*;

mod slot_changed_state;
pub use slot_changed_state::*;

mod cookie_response;
pub use cookie_response::*;

mod custom_payload_c2s;
pub use custom_payload_c2s::*;

mod debug_sample_subscription;
pub use debug_sample_subscription::*;

mod book_update;
pub use book_update::*;

mod query_entity_nbt;
pub use query_entity_nbt::*;

mod player_interact_entity;
pub use player_interact_entity::*;

mod jigsaw_generating;
pub use jigsaw_generating::*;

mod keep_alive_c2s;
pub use keep_alive_c2s::*;

mod update_difficulty_lock;
pub use update_difficulty_lock::*;

mod player_move_position_and_on_ground;
pub use player_move_position_and_on_ground::*;

mod player_move_full;
pub use player_move_full::*;

mod player_move_look_and_on_ground;
pub use player_move_look_and_on_ground::*;

mod player_move_on_ground_only;
pub use player_move_on_ground_only::*;

mod vehicle_move_c2s;
pub use vehicle_move_c2s::*;

mod boat_paddle_state;
pub use boat_paddle_state::*;

mod pick_from_inventory;
pub use pick_from_inventory::*;

mod query_ping;
pub use query_ping::*;

mod craft_request;
pub use craft_request::*;

mod update_player_abilities;
pub use update_player_abilities::*;

mod player_action;
pub use player_action::*;

mod client_command;
pub use client_command::*;

mod player_input;
pub use player_input::*;

mod common_pong;
pub use common_pong::*;

mod recipe_category_options;
pub use recipe_category_options::*;

mod recipe_book_data;
pub use recipe_book_data::*;

mod rename_item;
pub use rename_item::*;

mod resource_pack_status;
pub use resource_pack_status::*;

mod advancement_tab;
pub use advancement_tab::*;

mod select_merchant_trade;
pub use select_merchant_trade::*;

mod update_beacon;
pub use update_beacon::*;

mod update_selected_slot_c2s;
pub use update_selected_slot_c2s::*;

mod update_command_block;
pub use update_command_block::*;

mod update_command_block_minecart;
pub use update_command_block_minecart::*;

mod creative_inventory_action;
pub use creative_inventory_action::*;

mod update_jigsaw;
pub use update_jigsaw::*;

mod update_structure_block;
pub use update_structure_block::*;

mod update_sign;
pub use update_sign::*;

mod hand_swing;
pub use hand_swing::*;

mod spectator_teleport;
pub use spectator_teleport::*;

mod player_interact_block;
pub use player_interact_block::*;

mod player_interact_item;
pub use player_interact_item::*;

froglight_macros::frog_state! {
    Play,
    V1_21_2,
    Clientbound {
        0u32 => BundleDelimiterPacket,
        1u32 => EntitySpawnPacket,
        2u32 => ExperienceOrbSpawnPacket,
        3u32 => EntityAnimationPacket,
        4u32 => StatisticsPacket,
        5u32 => PlayerActionResponsePacket,
        6u32 => BlockBreakingProgressPacket,
        7u32 => BlockEntityUpdatePacket,
        8u32 => BlockEventPacket,
        9u32 => BlockUpdatePacket,
        10u32 => BossBarPacket,
        11u32 => DifficultyPacket,
        12u32 => ChunkSentPacket,
        13u32 => StartChunkSendPacket,
        14u32 => ChunkBiomeDataPacket,
        15u32 => ClearTitlePacket,
        16u32 => CommandSuggestionsPacket,
        17u32 => CommandTreePacket,
        18u32 => CloseScreenPacket,
        19u32 => InventoryPacket,
        20u32 => ScreenHandlerPropertyUpdatePacket,
        21u32 => ScreenHandlerSlotUpdatePacket,
        22u32 => CookieRequestPacket,
        23u32 => CooldownUpdatePacket,
        24u32 => ChatSuggestionsPacket,
        25u32 => CustomPayloadS2CPacket,
        26u32 => EntityDamagePacket,
        27u32 => DebugSamplePacket,
        28u32 => RemoveMessagePacket,
        29u32 => DisconnectPacket,
        30u32 => ProfilelessChatMessagePacket,
        31u32 => EntityStatusPacket,
        32u32 => EntityPositionSyncPacket,
        33u32 => ExplosionPacket,
        34u32 => UnloadChunkPacket,
        35u32 => GameStateChangePacket,
        36u32 => OpenHorseScreenPacket,
        37u32 => DamageTiltPacket,
        38u32 => WorldBorderInitializePacket,
        39u32 => KeepAliveS2CPacket,
        40u32 => ChunkDataPacket,
        41u32 => WorldEventPacket,
        42u32 => ParticlePacket,
        43u32 => LightUpdatePacket,
        44u32 => GameJoinPacket,
        45u32 => MapUpdatePacket,
        46u32 => SetTradeOffersPacket,
        47u32 => EntityMoveRelativePacket,
        48u32 => EntityRotateAndMoveRelativePacket,
        49u32 => MoveMinecartAlongTrackPacket,
        50u32 => EntityRotatePacket,
        51u32 => VehicleMoveS2CPacket,
        52u32 => OpenWrittenBookPacket,
        53u32 => OpenScreenPacket,
        54u32 => SignEditorOpenPacket,
        55u32 => CommonPingPacket,
        56u32 => PingResultPacket,
        57u32 => CraftFailedResponsePacket,
        58u32 => PlayerAbilitiesPacket,
        59u32 => ChatMessageS2CPacket,
        60u32 => EndCombatPacket,
        61u32 => EnterCombatPacket,
        62u32 => DeathMessagePacket,
        63u32 => PlayerRemovePacket,
        64u32 => PlayerListPacket,
        65u32 => LookAtPacket,
        66u32 => PlayerPositionLookPacket,
        67u32 => PlayerRotationS2CPaketPacket,
        68u32 => RecipeBookAddPacket,
        69u32 => RecipeBookRemovePacket,
        70u32 => RecipeBookSettingsPacket,
        71u32 => EntitiesDestroyPacket,
        72u32 => RemoveEntityStatusEffectPacket,
        73u32 => ScoreboardScoreResetPacket,
        74u32 => ResourcePackRemovePacket,
        75u32 => ResourcePackSendPacket,
        76u32 => PlayerRespawnPacket,
        77u32 => EntitySetHeadYawPacket,
        78u32 => ChunkDeltaUpdatePacket,
        79u32 => SelectAdvancementTabPacket,
        80u32 => ServerMetadataPacket,
        81u32 => OverlayMessagePacket,
        82u32 => WorldBorderCenterChangedPacket,
        83u32 => WorldBorderInterpolateSizePacket,
        84u32 => WorldBorderSizeChangedPacket,
        85u32 => WorldBorderWarningTimeChangedPacket,
        86u32 => WorldBorderWarningBlocksChangedPacket,
        87u32 => SetCameraEntityPacket,
        88u32 => ChunkRenderDistanceCenterPacket,
        89u32 => ChunkLoadDistancePacket,
        90u32 => SetCursorItemPacket,
        91u32 => PlayerSpawnPositionPacket,
        92u32 => ScoreboardDisplayPacket,
        93u32 => EntityTrackerUpdatePacket,
        94u32 => EntityAttachPacket,
        95u32 => EntityVelocityUpdatePacket,
        96u32 => EntityEquipmentUpdatePacket,
        97u32 => ExperienceBarUpdatePacket,
        98u32 => HealthUpdatePacket,
        99u32 => UpdateSelectedSlotS2CPacket,
        100u32 => ScoreboardObjectiveUpdatePacket,
        101u32 => EntityPassengersSetPacket,
        102u32 => SetPlayerInventoryPacket,
        103u32 => TeamPacket,
        104u32 => ScoreboardScoreUpdatePacket,
        105u32 => SimulationDistancePacket,
        106u32 => SubtitlePacket,
        107u32 => WorldTimeUpdatePacket,
        108u32 => TitlePacket,
        109u32 => TitleFadePacket,
        110u32 => PlaySoundFromEntityPacket,
        111u32 => PlaySoundPacket,
        112u32 => EnterReconfigurationPacket,
        113u32 => StopSoundPacket,
        114u32 => StoreCookiePacket,
        115u32 => GameMessagePacket,
        116u32 => PlayerListHeaderPacket,
        117u32 => NbtQueryResponsePacket,
        118u32 => ItemPickupAnimationPacket,
        119u32 => EntityPositionPacket,
        120u32 => UpdateTickRatePacket,
        121u32 => TickStepPacket,
        122u32 => ServerTransferPacket,
        123u32 => AdvancementUpdatePacket,
        124u32 => EntityAttributesPacket,
        125u32 => EntityStatusEffectPacket,
        126u32 => SynchronizeRecipesPacket,
        127u32 => SynchronizeTagsPacket,
        128u32 => ProjectilePowerPacket,
        129u32 => CustomReportDetailsPacket,
        130u32 => ServerLinksPacket,
    },
    Serverbound {
        0u32 => TeleportConfirmPacket,
        1u32 => QueryBlockNbtPacket,
        2u32 => BundleItemSelectedPacket,
        3u32 => UpdateDifficultyPacket,
        4u32 => MessageAcknowledgmentPacket,
        5u32 => CommandExecutionPacket,
        6u32 => ChatCommandSignedPacket,
        7u32 => ChatMessageC2SPacket,
        8u32 => PlayerSessionPacket,
        9u32 => AcknowledgeChunksPacket,
        10u32 => ClientStatusPacket,
        11u32 => ClientTickEndPacket,
        12u32 => ClientOptionsPacket,
        13u32 => RequestCommandCompletionsPacket,
        14u32 => AcknowledgeReconfigurationPacket,
        15u32 => ButtonClickPacket,
        16u32 => ClickSlotPacket,
        17u32 => CloseHandledScreenPacket,
        18u32 => SlotChangedStatePacket,
        19u32 => CookieResponsePacket,
        20u32 => CustomPayloadC2SPacket,
        21u32 => DebugSampleSubscriptionPacket,
        22u32 => BookUpdatePacket,
        23u32 => QueryEntityNbtPacket,
        24u32 => PlayerInteractEntityPacket,
        25u32 => JigsawGeneratingPacket,
        26u32 => KeepAliveC2SPacket,
        27u32 => UpdateDifficultyLockPacket,
        28u32 => PlayerMovePositionAndOnGroundPacket,
        29u32 => PlayerMoveFullPacket,
        30u32 => PlayerMoveLookAndOnGroundPacket,
        31u32 => PlayerMoveOnGroundOnlyPacket,
        32u32 => VehicleMoveC2SPacket,
        33u32 => BoatPaddleStatePacket,
        34u32 => PickFromInventoryPacket,
        35u32 => QueryPingPacket,
        36u32 => CraftRequestPacket,
        37u32 => UpdatePlayerAbilitiesPacket,
        38u32 => PlayerActionPacket,
        39u32 => ClientCommandPacket,
        40u32 => PlayerInputPacket,
        41u32 => CommonPongPacket,
        42u32 => RecipeCategoryOptionsPacket,
        43u32 => RecipeBookDataPacket,
        44u32 => RenameItemPacket,
        45u32 => ResourcePackStatusPacket,
        46u32 => AdvancementTabPacket,
        47u32 => SelectMerchantTradePacket,
        48u32 => UpdateBeaconPacket,
        49u32 => UpdateSelectedSlotC2SPacket,
        50u32 => UpdateCommandBlockPacket,
        51u32 => UpdateCommandBlockMinecartPacket,
        52u32 => CreativeInventoryActionPacket,
        53u32 => UpdateJigsawPacket,
        54u32 => UpdateStructureBlockPacket,
        55u32 => UpdateSignPacket,
        56u32 => HandSwingPacket,
        57u32 => SpectatorTeleportPacket,
        58u32 => PlayerInteractBlockPacket,
        59u32 => PlayerInteractItemPacket,
    },
}
