//! @generated by `froglight-generator` #e606248

use froglight_macros::FrogReadWrite;

use crate::common::{BlockPosition, ResourceKey};

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct PlayerRespawnPacket {
    pub field_0: ResourceKey,
    pub field_1: i64,
    pub field_2: u8,
    pub field_3: u8,
    pub field_4: bool,
    pub field_5: bool,
    pub field_6: ResourceKey,
    pub field_7: BlockPosition,
    pub field_8: Option<()>,
    #[frog(var)]
    pub field_9: u32,
    #[frog(var)]
    pub field_10: u32,
    pub field_11: u8,
}
