//! @generated by `froglight-generator` #8ddd9f0

use froglight_macros::FrogReadWrite;
use glam::Vec2;

#[derive(Debug, Clone, Copy, PartialEq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct PlayerRotationS2CPacket {
    pub rotation: Vec2,
}
