//! @generated by `froglight-generator` #8ddd9f0

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct ProfilelessChatMessagePacket {
    pub field_0: Text,
    #[frog(var)]
    pub field_1: u32,
    pub field_2: Text,
    pub field_3: Option<Text>,
}
