//! @generated by `froglight-generator` #e606248

use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct SignEditorOpenPacket {
    pub field_0: BlockPosition,
    pub field_1: bool,
}
