//! @generated by `froglight-generator` #8ddd9f0

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;
use uuid::Uuid;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deref, DerefMut, From, Into, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct SpectatorTeleportPacket {
    pub field_0: Uuid,
}
