//! @generated by `froglight-generator` #8ddd9f0

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, PartialEq, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct UpdateStructureBlockPacket {
    pub field_0: BlockPosition,
    pub field_1: Enum,
    pub field_2: Enum,
    pub field_3: CompactString,
    pub field_4: u8,
    pub field_5: u8,
    pub field_6: u8,
    pub field_7: u8,
    pub field_8: u8,
    pub field_9: u8,
    pub field_10: Enum,
    pub field_11: Enum,
    pub field_12: CompactString,
    pub field_13: f32,
    #[frog(var)]
    pub field_14: u64,
    pub field_15: u8,
}
