//! @generated by `froglight-generator` #8ddd9f0

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

use crate::common::BlockPosition;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct UpdateCommandBlockPacket {
    pub field_0: BlockPosition,
    pub field_1: CompactString,
    pub field_2: Enum,
    pub field_3: u8,
}
