//! @generated by `froglight-generator` #e606248

use compact_str::CompactString;
use froglight_macros::FrogReadWrite;

use crate::common::{BlockPosition, ResourceKey};

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct UpdateJigsawPacket {
    pub field_0: BlockPosition,
    pub field_1: ResourceKey,
    pub field_2: ResourceKey,
    pub field_3: ResourceKey,
    pub field_4: CompactString,
    pub field_5: CompactString,
    #[frog(var)]
    pub field_6: u32,
    #[frog(var)]
    pub field_7: u32,
}
