// This file is automatically generated!
// Do not manually edit it!

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttachmentAttribute {
    Floor,
    Ceiling,
    SingleWall,
    DoubleWall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AxisAttribute {
    X,
    Y,
    Z,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BambooLeavesAttribute {
    None,
    Small,
    Large,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BedPartAttribute {
    Head,
    Foot,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockHalfAttribute {
    Top,
    Bottom,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ChestTypeAttribute {
    Single,
    Left,
    Right,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ComparatorModeAttribute {
    Compare,
    Subtract,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DoorHingeAttribute {
    Left,
    Right,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DoubleBlockHalfAttribute {
    Upper,
    Lower,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EastWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EastWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HorizontalAxisAttribute {
    X,
    Y,
    Z,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstrumentAttribute {
    Harp,
    Basedrum,
    Snare,
    Hat,
    Bass,
    Flute,
    Bell,
    Guitar,
    Chime,
    Xylophone,
    IronXylophone,
    CowBell,
    Didgeridoo,
    Bit,
    Banjo,
    Pling,
    Zombie,
    Skeleton,
    Creeper,
    Dragon,
    WitherSkeleton,
    Piglin,
    CustomHead,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NorthWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NorthWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OrientationAttribute {
    DownEast,
    DownNorth,
    DownSouth,
    DownWest,
    UpEast,
    UpNorth,
    UpSouth,
    UpWest,
    WestUp,
    EastUp,
    NorthUp,
    SouthUp,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PistonTypeAttribute {
    Default,
    Sticky,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RailShapeAttribute {
    NorthSouth,
    EastWest,
    AscendingEast,
    AscendingWest,
    AscendingNorth,
    AscendingSouth,
    SouthEast,
    SouthWest,
    NorthWest,
    NorthEast,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SculkSensorPhaseAttribute {
    Inactive,
    Active,
    Cooldown,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SlabTypeAttribute {
    Top,
    Bottom,
    Double,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SouthWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SouthWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StairShapeAttribute {
    Straight,
    InnerLeft,
    InnerRight,
    OuterLeft,
    OuterRight,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StraightRailShapeAttribute {
    NorthSouth,
    EastWest,
    AscendingEast,
    AscendingWest,
    AscendingNorth,
    AscendingSouth,
    SouthEast,
    SouthWest,
    NorthWest,
    NorthEast,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StructureBlockModeAttribute {
    Save,
    Load,
    Corner,
    Data,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThicknessAttribute {
    TipMerge,
    Tip,
    Frustum,
    Middle,
    Base,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TiltAttribute {
    None,
    Unstable,
    Partial,
    Full,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WallMountLocationAttribute {
    Floor,
    Wall,
    Ceiling,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WestWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WestWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DirectionAttribute {
    Down,
    Up,
    North,
    South,
    West,
    East,
}
