//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_common::identifier::Identifier;

use crate::common::UnsizedBuffer;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct LoginQueryRequestS2CPacket {
    #[cfg_attr(feature = "io", frog(var))]
    pub query_id: u32,
    pub identifier: Identifier,
    pub payload: UnsizedBuffer<[u8; 16]>,
}
