//! [`Configuration`] state packets for [`1.20.3`]
//!
//! @generated by `froglight-generator #00f1b4b`
#![allow(missing_docs)]

mod custompayloads2cpacket;
pub use custompayloads2cpacket::*;

mod disconnects2cpacket;
pub use disconnects2cpacket::*;

mod readys2cpacket;
pub use readys2cpacket::*;

mod keepalives2cpacket;
pub use keepalives2cpacket::*;

mod commonpings2cpacket;
pub use commonpings2cpacket::*;

mod dynamicregistriess2cpacket;
pub use dynamicregistriess2cpacket::*;

mod resourcepackremoves2cpacket;
pub use resourcepackremoves2cpacket::*;

mod resourcepacksends2cpacket;
pub use resourcepacksends2cpacket::*;

mod featuress2cpacket;
pub use featuress2cpacket::*;

mod synchronizetagss2cpacket;
pub use synchronizetagss2cpacket::*;

mod clientoptionsc2spacket;
pub use clientoptionsc2spacket::*;

mod custompayloadc2spacket;
pub use custompayloadc2spacket::*;

mod readyc2spacket;
pub use readyc2spacket::*;

mod keepalivec2spacket;
pub use keepalivec2spacket::*;

mod commonpongc2spacket;
pub use commonpongc2spacket::*;

mod resourcepackstatusc2spacket;
pub use resourcepackstatusc2spacket::*;
