//! Protocol `768`
//!
//! Used by Minecraft `1.21.2` - `1.21.2`
//!
//! @generated by `froglight-generator` #e606248
#![allow(clippy::module_inception)]

pub mod configuration;
pub mod handshake;
pub mod login;
pub mod play;
pub mod status;

/// Protocol `768`
///
/// Used by Minecraft `1.21.2` - `1.21.2`
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "bevy", derive(bevy_reflect::Reflect))]
pub struct V1_21_2;
impl crate::traits::Version for V1_21_2 {
    const ID: i32 = 768;
}
