//! @generated by `froglight-generator` #ecfea09

use derive_more::{Deref, DerefMut, From, Into};
use froglight_macros::FrogReadWrite;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Deref,
    DerefMut,
    From,
    Into,
    Serialize,
    Deserialize,
    FrogReadWrite,
)]
#[frog(json)]
pub struct QueryResponsePacket {
    pub field_0: Json,
}
