//! Generated registries and their implementations.
//!
//! @generated by `froglight-generator #NULL`

mod generated;
// pub use generated::*;

mod v1_20_0;
mod v1_20_2;
mod v1_20_3;

#[doc(hidden)]
pub(super) fn build(_app: &mut bevy_app::App) {}
