//! Generated registries and their implementations.
//!
//! @generated by `froglight-generator #NULL`
#![allow(missing_docs)]

mod generated;
// pub use generated::*;

mod v1_21_0;

#[doc(hidden)]
pub(super) fn build(app: &mut bevy_app::App) { generated::build(app); }
