// This file is automatically generated!
// Do not manually edit it!

use super::{
    AttachmentAttribute, AxisAttribute, BambooLeavesAttribute, BedPartAttribute,
    BlockHalfAttribute, ChestTypeAttribute, ComparatorModeAttribute, DirectionAttribute,
    DoorHingeAttribute, DoubleBlockHalfAttribute, EastWallShapeAttribute,
    EastWireConnectionAttribute, HorizontalAxisAttribute, InstrumentAttribute,
    NorthWallShapeAttribute, NorthWireConnectionAttribute, OrientationAttribute,
    PistonTypeAttribute, RailShapeAttribute, SculkSensorPhaseAttribute, SlabTypeAttribute,
    SouthWallShapeAttribute, SouthWireConnectionAttribute, StairShapeAttribute,
    StraightRailShapeAttribute, StructureBlockModeAttribute, ThicknessAttribute, TiltAttribute,
    WallMountLocationAttribute, WestWallShapeAttribute, WestWireConnectionAttribute,
};

use std::fmt::Debug;
pub trait BlockAttributeTrait: Debug + Send + Sync {
    fn age_1(&self) -> Option<i32> { None }
    fn age_15(&self) -> Option<i32> { None }
    fn age_2(&self) -> Option<i32> { None }
    fn age_25(&self) -> Option<i32> { None }
    fn age_3(&self) -> Option<i32> { None }
    fn age_4(&self) -> Option<i32> { None }
    fn age_5(&self) -> Option<i32> { None }
    fn age_7(&self) -> Option<i32> { None }
    fn attached(&self) -> Option<bool> { None }
    fn attachment(&self) -> Option<AttachmentAttribute> { None }
    fn axis(&self) -> Option<AxisAttribute> { None }
    fn bamboo_leaves(&self) -> Option<BambooLeavesAttribute> { None }
    fn bed_part(&self) -> Option<BedPartAttribute> { None }
    fn berries(&self) -> Option<bool> { None }
    fn bites(&self) -> Option<i32> { None }
    fn block_half(&self) -> Option<BlockHalfAttribute> { None }
    fn bloom(&self) -> Option<bool> { None }
    fn bottom(&self) -> Option<bool> { None }
    fn candles(&self) -> Option<i32> { None }
    fn can_summon(&self) -> Option<bool> { None }
    fn charges(&self) -> Option<i32> { None }
    fn chest_type(&self) -> Option<ChestTypeAttribute> { None }
    fn comparator_mode(&self) -> Option<ComparatorModeAttribute> { None }
    fn conditional(&self) -> Option<bool> { None }
    fn cracked(&self) -> Option<bool> { None }
    fn delay(&self) -> Option<i32> { None }
    fn disarmed(&self) -> Option<bool> { None }
    fn distance_0_7(&self) -> Option<i32> { None }
    fn distance_1_7(&self) -> Option<i32> { None }
    fn door_hinge(&self) -> Option<DoorHingeAttribute> { None }
    fn double_block_half(&self) -> Option<DoubleBlockHalfAttribute> { None }
    fn down(&self) -> Option<bool> { None }
    fn drag(&self) -> Option<bool> { None }
    fn dusted(&self) -> Option<i32> { None }
    fn east(&self) -> Option<bool> { None }
    fn east_wall_shape(&self) -> Option<EastWallShapeAttribute> { None }
    fn east_wire_connection(&self) -> Option<EastWireConnectionAttribute> { None }
    fn eggs(&self) -> Option<i32> { None }
    fn enabled(&self) -> Option<bool> { None }
    fn extended(&self) -> Option<bool> { None }
    fn eye(&self) -> Option<bool> { None }
    fn facing(&self) -> Option<DirectionAttribute> { None }
    fn falling(&self) -> Option<bool> { None }
    fn flower_amount(&self) -> Option<i32> { None }
    fn hanging(&self) -> Option<bool> { None }
    fn has_book(&self) -> Option<bool> { None }
    fn has_bottle_0(&self) -> Option<bool> { None }
    fn has_bottle_1(&self) -> Option<bool> { None }
    fn has_bottle_2(&self) -> Option<bool> { None }
    fn has_record(&self) -> Option<bool> { None }
    fn hatch(&self) -> Option<i32> { None }
    fn honey_level(&self) -> Option<i32> { None }
    fn hopper_facing(&self) -> Option<DirectionAttribute> { None }
    fn horizontal_axis(&self) -> Option<HorizontalAxisAttribute> { None }
    fn horizontal_facing(&self) -> Option<DirectionAttribute> { None }
    fn instrument(&self) -> Option<InstrumentAttribute> { None }
    fn inverted(&self) -> Option<bool> { None }
    fn in_wall(&self) -> Option<bool> { None }
    fn layers(&self) -> Option<i32> { None }
    fn level_15(&self) -> Option<i32> { None }
    fn level_1_8(&self) -> Option<i32> { None }
    fn level_3(&self) -> Option<i32> { None }
    fn level_8(&self) -> Option<i32> { None }
    fn lit(&self) -> Option<bool> { None }
    fn locked(&self) -> Option<bool> { None }
    fn moisture(&self) -> Option<i32> { None }
    fn north(&self) -> Option<bool> { None }
    fn north_wall_shape(&self) -> Option<NorthWallShapeAttribute> { None }
    fn north_wire_connection(&self) -> Option<NorthWireConnectionAttribute> { None }
    fn note(&self) -> Option<i32> { None }
    fn occupied(&self) -> Option<bool> { None }
    fn open(&self) -> Option<bool> { None }
    fn orientation(&self) -> Option<OrientationAttribute> { None }
    fn persistent(&self) -> Option<bool> { None }
    fn pickles(&self) -> Option<i32> { None }
    fn piston_type(&self) -> Option<PistonTypeAttribute> { None }
    fn power(&self) -> Option<i32> { None }
    fn powered(&self) -> Option<bool> { None }
    fn rail_shape(&self) -> Option<RailShapeAttribute> { None }
    fn rotation(&self) -> Option<i32> { None }
    fn sculk_sensor_phase(&self) -> Option<SculkSensorPhaseAttribute> { None }
    fn short(&self) -> Option<bool> { None }
    fn shrieking(&self) -> Option<bool> { None }
    fn signal_fire(&self) -> Option<bool> { None }
    fn slab_type(&self) -> Option<SlabTypeAttribute> { None }
    fn slot_0_occupied(&self) -> Option<bool> { None }
    fn slot_1_occupied(&self) -> Option<bool> { None }
    fn slot_2_occupied(&self) -> Option<bool> { None }
    fn slot_3_occupied(&self) -> Option<bool> { None }
    fn slot_4_occupied(&self) -> Option<bool> { None }
    fn slot_5_occupied(&self) -> Option<bool> { None }
    fn snowy(&self) -> Option<bool> { None }
    fn south(&self) -> Option<bool> { None }
    fn south_wall_shape(&self) -> Option<SouthWallShapeAttribute> { None }
    fn south_wire_connection(&self) -> Option<SouthWireConnectionAttribute> { None }
    fn stage(&self) -> Option<i32> { None }
    fn stair_shape(&self) -> Option<StairShapeAttribute> { None }
    fn straight_rail_shape(&self) -> Option<StraightRailShapeAttribute> { None }
    fn structure_block_mode(&self) -> Option<StructureBlockModeAttribute> { None }
    fn thickness(&self) -> Option<ThicknessAttribute> { None }
    fn tilt(&self) -> Option<TiltAttribute> { None }
    fn triggered(&self) -> Option<bool> { None }
    fn unstable(&self) -> Option<bool> { None }
    fn up(&self) -> Option<bool> { None }
    fn vertical_direction(&self) -> Option<DirectionAttribute> { None }
    fn wall_mount_location(&self) -> Option<WallMountLocationAttribute> { None }
    fn waterlogged(&self) -> Option<bool> { None }
    fn west(&self) -> Option<bool> { None }
    fn west_wall_shape(&self) -> Option<WestWallShapeAttribute> { None }
    fn west_wire_connection(&self) -> Option<WestWireConnectionAttribute> { None }
}
