// This file is automatically generated!
// Run mc-rs-gen to regenerate it!

#![allow(dead_code)]
pub mod statics;
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
pub struct BlockAttributes {
    pub age_1: Option<i32>,
    pub age_15: Option<i32>,
    pub age_2: Option<i32>,
    pub age_25: Option<i32>,
    pub age_3: Option<i32>,
    pub age_4: Option<i32>,
    pub age_5: Option<i32>,
    pub age_7: Option<i32>,
    pub attached: Option<bool>,
    pub attachment: Option<AttachmentAttribute>,
    pub axis: Option<AxisAttribute>,
    pub bamboo_leaves: Option<BambooLeavesAttribute>,
    pub bed_part: Option<BedPartAttribute>,
    pub berries: Option<bool>,
    pub bites: Option<i32>,
    pub block_half: Option<BlockHalfAttribute>,
    pub bloom: Option<bool>,
    pub bottom: Option<bool>,
    pub candles: Option<i32>,
    pub can_summon: Option<bool>,
    pub charges: Option<i32>,
    pub chest_type: Option<ChestTypeAttribute>,
    pub comparator_mode: Option<ComparatorModeAttribute>,
    pub conditional: Option<bool>,
    pub cracked: Option<bool>,
    pub delay: Option<i32>,
    pub disarmed: Option<bool>,
    pub distance_0_7: Option<i32>,
    pub distance_1_7: Option<i32>,
    pub door_hinge: Option<DoorHingeAttribute>,
    pub double_block_half: Option<DoubleBlockHalfAttribute>,
    pub down: Option<bool>,
    pub drag: Option<bool>,
    pub dusted: Option<i32>,
    pub east: Option<bool>,
    pub east_wall_shape: Option<EastWallShapeAttribute>,
    pub east_wire_connection: Option<EastWireConnectionAttribute>,
    pub eggs: Option<i32>,
    pub enabled: Option<bool>,
    pub extended: Option<bool>,
    pub eye: Option<bool>,
    pub facing: Option<DirectionAttribute>,
    pub falling: Option<bool>,
    pub flower_amount: Option<i32>,
    pub hanging: Option<bool>,
    pub has_book: Option<bool>,
    pub has_bottle_0: Option<bool>,
    pub has_bottle_1: Option<bool>,
    pub has_bottle_2: Option<bool>,
    pub has_record: Option<bool>,
    pub hatch: Option<i32>,
    pub honey_level: Option<i32>,
    pub hopper_facing: Option<DirectionAttribute>,
    pub horizontal_axis: Option<HorizontalAxisAttribute>,
    pub horizontal_facing: Option<DirectionAttribute>,
    pub instrument: Option<InstrumentAttribute>,
    pub inverted: Option<bool>,
    pub in_wall: Option<bool>,
    pub layers: Option<i32>,
    pub level_15: Option<i32>,
    pub level_1_8: Option<i32>,
    pub level_3: Option<i32>,
    pub level_8: Option<i32>,
    pub lit: Option<bool>,
    pub locked: Option<bool>,
    pub moisture: Option<i32>,
    pub north: Option<bool>,
    pub north_wall_shape: Option<NorthWallShapeAttribute>,
    pub north_wire_connection: Option<NorthWireConnectionAttribute>,
    pub note: Option<i32>,
    pub occupied: Option<bool>,
    pub open: Option<bool>,
    pub orientation: Option<OrientationAttribute>,
    pub persistent: Option<bool>,
    pub pickles: Option<i32>,
    pub piston_type: Option<PistonTypeAttribute>,
    pub power: Option<i32>,
    pub powered: Option<bool>,
    pub rail_shape: Option<RailShapeAttribute>,
    pub rotation: Option<i32>,
    pub sculk_sensor_phase: Option<SculkSensorPhaseAttribute>,
    pub short: Option<bool>,
    pub shrieking: Option<bool>,
    pub signal_fire: Option<bool>,
    pub slab_type: Option<SlabTypeAttribute>,
    pub slot_0_occupied: Option<bool>,
    pub slot_1_occupied: Option<bool>,
    pub slot_2_occupied: Option<bool>,
    pub slot_3_occupied: Option<bool>,
    pub slot_4_occupied: Option<bool>,
    pub slot_5_occupied: Option<bool>,
    pub snowy: Option<bool>,
    pub south: Option<bool>,
    pub south_wall_shape: Option<SouthWallShapeAttribute>,
    pub south_wire_connection: Option<SouthWireConnectionAttribute>,
    pub stage: Option<i32>,
    pub stair_shape: Option<StairShapeAttribute>,
    pub straight_rail_shape: Option<StraightRailShapeAttribute>,
    pub structure_block_mode: Option<StructureBlockModeAttribute>,
    pub thickness: Option<ThicknessAttribute>,
    pub tilt: Option<TiltAttribute>,
    pub triggered: Option<bool>,
    pub unstable: Option<bool>,
    pub up: Option<bool>,
    pub vertical_direction: Option<DirectionAttribute>,
    pub wall_mount_location: Option<WallMountLocationAttribute>,
    pub waterlogged: Option<bool>,
    pub west: Option<bool>,
    pub west_wall_shape: Option<WestWallShapeAttribute>,
    pub west_wire_connection: Option<WestWireConnectionAttribute>,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttachmentAttribute {
    Floor,
    Ceiling,
    SingleWall,
    DoubleWall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AxisAttribute {
    X,
    Y,
    Z,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BambooLeavesAttribute {
    None,
    Small,
    Large,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BedPartAttribute {
    Head,
    Foot,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockHalfAttribute {
    Top,
    Bottom,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ChestTypeAttribute {
    Single,
    Left,
    Right,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ComparatorModeAttribute {
    Compare,
    Subtract,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DoorHingeAttribute {
    Left,
    Right,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DoubleBlockHalfAttribute {
    Upper,
    Lower,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EastWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EastWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HorizontalAxisAttribute {
    X,
    Y,
    Z,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstrumentAttribute {
    Harp,
    Basedrum,
    Snare,
    Hat,
    Bass,
    Flute,
    Bell,
    Guitar,
    Chime,
    Xylophone,
    IronXylophone,
    CowBell,
    Didgeridoo,
    Bit,
    Banjo,
    Pling,
    Zombie,
    Skeleton,
    Creeper,
    Dragon,
    WitherSkeleton,
    Piglin,
    CustomHead,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NorthWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NorthWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OrientationAttribute {
    DownEast,
    DownNorth,
    DownSouth,
    DownWest,
    UpEast,
    UpNorth,
    UpSouth,
    UpWest,
    WestUp,
    EastUp,
    NorthUp,
    SouthUp,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PistonTypeAttribute {
    Default,
    Sticky,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RailShapeAttribute {
    NorthSouth,
    EastWest,
    AscendingEast,
    AscendingWest,
    AscendingNorth,
    AscendingSouth,
    SouthEast,
    SouthWest,
    NorthWest,
    NorthEast,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SculkSensorPhaseAttribute {
    Inactive,
    Active,
    Cooldown,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SlabTypeAttribute {
    Top,
    Bottom,
    Double,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SouthWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SouthWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StairShapeAttribute {
    Straight,
    InnerLeft,
    InnerRight,
    OuterLeft,
    OuterRight,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StraightRailShapeAttribute {
    NorthSouth,
    EastWest,
    AscendingEast,
    AscendingWest,
    AscendingNorth,
    AscendingSouth,
    SouthEast,
    SouthWest,
    NorthWest,
    NorthEast,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StructureBlockModeAttribute {
    Save,
    Load,
    Corner,
    Data,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThicknessAttribute {
    TipMerge,
    Tip,
    Frustum,
    Middle,
    Base,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TiltAttribute {
    None,
    Unstable,
    Partial,
    Full,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WallMountLocationAttribute {
    Floor,
    Wall,
    Ceiling,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WestWallShapeAttribute {
    None,
    Low,
    Tall,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WestWireConnectionAttribute {
    Up,
    Side,
    None,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DirectionAttribute {
    Down,
    Up,
    North,
    South,
    West,
    East,
}
