pub mod clientboundadvancementupdatepacket;
pub mod clientboundblockbreakingprogresspacket;
pub mod clientboundblockentityupdatepacket;
pub mod clientboundblockeventpacket;
pub mod clientboundblockupdatepacket;
pub mod clientboundbossbarpacket;
pub mod clientboundbundlepacket;
pub mod clientboundchatmessagepacket;
pub mod clientboundchatsuggestionspacket;
pub mod clientboundchunkbiomedatapacket;
pub mod clientboundchunkdatapacket;
pub mod clientboundchunkdeltaupdatepacket;
pub mod clientboundchunkloaddistancepacket;
pub mod clientboundchunkrenderdistancecenterpacket;
pub mod clientboundcleartitlepacket;
pub mod clientboundclosescreenpacket;
pub mod clientboundcommandsuggestionspacket;
pub mod clientboundcommandtreepacket;
pub mod clientboundcooldownupdatepacket;
pub mod clientboundcraftfailedresponsepacket;
pub mod clientboundcustompayloadpacket;
pub mod clientbounddamagetiltpacket;
pub mod clientbounddeathmessagepacket;
pub mod clientbounddifficultypacket;
pub mod clientbounddisconnectpacket;
pub mod clientboundendcombatpacket;
pub mod clientboundentercombatpacket;
pub mod clientboundentitiesdestroypacket;
pub mod clientboundentityanimationpacket;
pub mod clientboundentityattachpacket;
pub mod clientboundentityattributespacket;
pub mod clientboundentitydamagepacket;
pub mod clientboundentityequipmentupdatepacket;
pub mod clientboundentitymoverelativepacket;
pub mod clientboundentitypassengerssetpacket;
pub mod clientboundentitypositionpacket;
pub mod clientboundentityrotateandmoverelativepacket;
pub mod clientboundentityrotatepacket;
pub mod clientboundentitysetheadyawpacket;
pub mod clientboundentityspawnpacket;
pub mod clientboundentitystatuseffectpacket;
pub mod clientboundentitystatuspacket;
pub mod clientboundentitytrackerupdatepacket;
pub mod clientboundentityvelocityupdatepacket;
pub mod clientboundexperiencebarupdatepacket;
pub mod clientboundexperienceorbspawnpacket;
pub mod clientboundexplosionpacket;
pub mod clientboundfeaturespacket;
pub mod clientboundgamejoinpacket;
pub mod clientboundgamemessagepacket;
pub mod clientboundgamestatechangepacket;
pub mod clientboundhealthupdatepacket;
pub mod clientboundinventorypacket;
pub mod clientbounditempickupanimationpacket;
pub mod clientboundkeepalivepacket;
pub mod clientboundlightupdatepacket;
pub mod clientboundlookatpacket;
pub mod clientboundmapupdatepacket;
pub mod clientboundnbtqueryresponsepacket;
pub mod clientboundopenhorsescreenpacket;
pub mod clientboundopenscreenpacket;
pub mod clientboundopenwrittenbookpacket;
pub mod clientboundoverlaymessagepacket;
pub mod clientboundparticlepacket;
pub mod clientboundplayerabilitiespacket;
pub mod clientboundplayeractionresponsepacket;
pub mod clientboundplayerlistheaderpacket;
pub mod clientboundplayerlistpacket;
pub mod clientboundplayerpositionlookpacket;
pub mod clientboundplayerremovepacket;
pub mod clientboundplayerrespawnpacket;
pub mod clientboundplayerspawnpacket;
pub mod clientboundplayerspawnpositionpacket;
pub mod clientboundplaypingpacket;
pub mod clientboundplaysoundfromentitypacket;
pub mod clientboundplaysoundpacket;
pub mod clientboundprofilelesschatmessagepacket;
pub mod clientboundremoveentitystatuseffectpacket;
pub mod clientboundremovemessagepacket;
pub mod clientboundresourcepacksendpacket;
pub mod clientboundscoreboarddisplaypacket;
pub mod clientboundscoreboardobjectiveupdatepacket;
pub mod clientboundscoreboardplayerupdatepacket;
pub mod clientboundscreenhandlerpropertyupdatepacket;
pub mod clientboundscreenhandlerslotupdatepacket;
pub mod clientboundselectadvancementtabpacket;
pub mod clientboundservermetadatapacket;
pub mod clientboundsetcameraentitypacket;
pub mod clientboundsettradeofferspacket;
pub mod clientboundsigneditoropenpacket;
pub mod clientboundsimulationdistancepacket;
pub mod clientboundstatisticspacket;
pub mod clientboundstopsoundpacket;
pub mod clientboundsubtitlepacket;
pub mod clientboundsynchronizerecipespacket;
pub mod clientboundsynchronizetagspacket;
pub mod clientboundteampacket;
pub mod clientboundtitlefadepacket;
pub mod clientboundtitlepacket;
pub mod clientboundunloadchunkpacket;
pub mod clientboundunlockrecipespacket;
pub mod clientboundupdateselectedslotpacket;
pub mod clientboundvehiclemovepacket;
pub mod clientboundworldbordercenterchangedpacket;
pub mod clientboundworldborderinitializepacket;
pub mod clientboundworldborderinterpolatesizepacket;
pub mod clientboundworldbordersizechangedpacket;
pub mod clientboundworldborderwarningblockschangedpacket;
pub mod clientboundworldborderwarningtimechangedpacket;
pub mod clientboundworldeventpacket;
pub mod clientboundworldtimeupdatepacket;
pub mod serverboundadvancementtabpacket;
pub mod serverboundboatpaddlestatepacket;
pub mod serverboundbookupdatepacket;
pub mod serverboundbuttonclickpacket;
pub mod serverboundchatmessagepacket;
pub mod serverboundclickslotpacket;
pub mod serverboundclientcommandpacket;
pub mod serverboundclientsettingspacket;
pub mod serverboundclientstatuspacket;
pub mod serverboundclosehandledscreenpacket;
pub mod serverboundcommandexecutionpacket;
pub mod serverboundcraftrequestpacket;
pub mod serverboundcreativeinventoryactionpacket;
pub mod serverboundcustompayloadpacket;
pub mod serverboundhandswingpacket;
pub mod serverboundjigsawgeneratingpacket;
pub mod serverboundkeepalivepacket;
pub mod serverboundmessageacknowledgmentpacket;
pub mod serverboundpickfrominventorypacket;
pub mod serverboundplayeractionpacket;
pub mod serverboundplayerinputpacket;
pub mod serverboundplayerinteractblockpacket;
pub mod serverboundplayerinteractentitypacket;
pub mod serverboundplayerinteractitempacket;
pub mod serverboundplayermovefullpacket;
pub mod serverboundplayermovelookandongroundpacket;
pub mod serverboundplayermoveongroundonlypacket;
pub mod serverboundplayermovepositionandongroundpacket;
pub mod serverboundplayersessionpacket;
pub mod serverboundplaypongpacket;
pub mod serverboundqueryblocknbtpacket;
pub mod serverboundqueryentitynbtpacket;
pub mod serverboundrecipebookdatapacket;
pub mod serverboundrecipecategoryoptionspacket;
pub mod serverboundrenameitempacket;
pub mod serverboundrequestcommandcompletionspacket;
pub mod serverboundresourcepackstatuspacket;
pub mod serverboundselectmerchanttradepacket;
pub mod serverboundspectatorteleportpacket;
pub mod serverboundteleportconfirmpacket;
pub mod serverboundupdatebeaconpacket;
pub mod serverboundupdatecommandblockminecartpacket;
pub mod serverboundupdatecommandblockpacket;
pub mod serverboundupdatedifficultylockpacket;
pub mod serverboundupdatedifficultypacket;
pub mod serverboundupdatejigsawpacket;
pub mod serverboundupdateplayerabilitiespacket;
pub mod serverboundupdateselectedslotpacket;
pub mod serverboundupdatesignpacket;
pub mod serverboundupdatestructureblockpacket;
pub mod serverboundvehiclemovepacket;

use super::V1_20_0;
use crate::versions::state::Play;
use mc_rs_macros::impl_state;

impl_state!(
    Play,
    V1_20_0,
    Clientbound => {
        0x0 => clientboundbundlepacket::ClientboundBundlePacket,
        0x1 => clientboundentityspawnpacket::ClientboundEntitySpawnPacket,
        0x2 => clientboundexperienceorbspawnpacket::ClientboundExperienceOrbSpawnPacket,
        0x3 => clientboundplayerspawnpacket::ClientboundPlayerSpawnPacket,
        0x4 => clientboundentityanimationpacket::ClientboundEntityAnimationPacket,
        0x5 => clientboundstatisticspacket::ClientboundStatisticsPacket,
        0x6 => clientboundplayeractionresponsepacket::ClientboundPlayerActionResponsePacket,
        0x7 => clientboundblockbreakingprogresspacket::ClientboundBlockBreakingProgressPacket,
        0x8 => clientboundblockentityupdatepacket::ClientboundBlockEntityUpdatePacket,
        0x9 => clientboundblockeventpacket::ClientboundBlockEventPacket,
        0xa => clientboundblockupdatepacket::ClientboundBlockUpdatePacket,
        0xb => clientboundbossbarpacket::ClientboundBossBarPacket,
        0xc => clientbounddifficultypacket::ClientboundDifficultyPacket,
        0xd => clientboundchunkbiomedatapacket::ClientboundChunkBiomeDataPacket,
        0xe => clientboundcleartitlepacket::ClientboundClearTitlePacket,
        0xf => clientboundcommandsuggestionspacket::ClientboundCommandSuggestionsPacket,
        0x10 => clientboundcommandtreepacket::ClientboundCommandTreePacket,
        0x11 => clientboundclosescreenpacket::ClientboundCloseScreenPacket,
        0x12 => clientboundinventorypacket::ClientboundInventoryPacket,
        0x13 => clientboundscreenhandlerpropertyupdatepacket::ClientboundScreenHandlerPropertyUpdatePacket,
        0x14 => clientboundscreenhandlerslotupdatepacket::ClientboundScreenHandlerSlotUpdatePacket,
        0x15 => clientboundcooldownupdatepacket::ClientboundCooldownUpdatePacket,
        0x16 => clientboundchatsuggestionspacket::ClientboundChatSuggestionsPacket,
        0x17 => clientboundcustompayloadpacket::ClientboundCustomPayloadPacket,
        0x18 => clientboundentitydamagepacket::ClientboundEntityDamagePacket,
        0x19 => clientboundremovemessagepacket::ClientboundRemoveMessagePacket,
        0x1a => clientbounddisconnectpacket::ClientboundDisconnectPacket,
        0x1b => clientboundprofilelesschatmessagepacket::ClientboundProfilelessChatMessagePacket,
        0x1c => clientboundentitystatuspacket::ClientboundEntityStatusPacket,
        0x1d => clientboundexplosionpacket::ClientboundExplosionPacket,
        0x1e => clientboundunloadchunkpacket::ClientboundUnloadChunkPacket,
        0x1f => clientboundgamestatechangepacket::ClientboundGameStateChangePacket,
        0x20 => clientboundopenhorsescreenpacket::ClientboundOpenHorseScreenPacket,
        0x21 => clientbounddamagetiltpacket::ClientboundDamageTiltPacket,
        0x22 => clientboundworldborderinitializepacket::ClientboundWorldBorderInitializePacket,
        0x23 => clientboundkeepalivepacket::ClientboundKeepAlivePacket,
        0x24 => clientboundchunkdatapacket::ClientboundChunkDataPacket,
        0x25 => clientboundworldeventpacket::ClientboundWorldEventPacket,
        0x26 => clientboundparticlepacket::ClientboundParticlePacket,
        0x27 => clientboundlightupdatepacket::ClientboundLightUpdatePacket,
        0x28 => clientboundgamejoinpacket::ClientboundGameJoinPacket,
        0x29 => clientboundmapupdatepacket::ClientboundMapUpdatePacket,
        0x2a => clientboundsettradeofferspacket::ClientboundSetTradeOffersPacket,
        0x2b => clientboundentitymoverelativepacket::ClientboundEntityMoveRelativePacket,
        0x2c => clientboundentityrotateandmoverelativepacket::ClientboundEntityRotateAndMoveRelativePacket,
        0x2d => clientboundentityrotatepacket::ClientboundEntityRotatePacket,
        0x2e => clientboundvehiclemovepacket::ClientboundVehicleMovePacket,
        0x2f => clientboundopenwrittenbookpacket::ClientboundOpenWrittenBookPacket,
        0x30 => clientboundopenscreenpacket::ClientboundOpenScreenPacket,
        0x31 => clientboundsigneditoropenpacket::ClientboundSignEditorOpenPacket,
        0x32 => clientboundplaypingpacket::ClientboundPlayPingPacket,
        0x33 => clientboundcraftfailedresponsepacket::ClientboundCraftFailedResponsePacket,
        0x34 => clientboundplayerabilitiespacket::ClientboundPlayerAbilitiesPacket,
        0x35 => clientboundchatmessagepacket::ClientboundChatMessagePacket,
        0x36 => clientboundendcombatpacket::ClientboundEndCombatPacket,
        0x37 => clientboundentercombatpacket::ClientboundEnterCombatPacket,
        0x38 => clientbounddeathmessagepacket::ClientboundDeathMessagePacket,
        0x39 => clientboundplayerremovepacket::ClientboundPlayerRemovePacket,
        0x3a => clientboundplayerlistpacket::ClientboundPlayerListPacket,
        0x3b => clientboundlookatpacket::ClientboundLookAtPacket,
        0x3c => clientboundplayerpositionlookpacket::ClientboundPlayerPositionLookPacket,
        0x3d => clientboundunlockrecipespacket::ClientboundUnlockRecipesPacket,
        0x3e => clientboundentitiesdestroypacket::ClientboundEntitiesDestroyPacket,
        0x3f => clientboundremoveentitystatuseffectpacket::ClientboundRemoveEntityStatusEffectPacket,
        0x40 => clientboundresourcepacksendpacket::ClientboundResourcePackSendPacket,
        0x41 => clientboundplayerrespawnpacket::ClientboundPlayerRespawnPacket,
        0x42 => clientboundentitysetheadyawpacket::ClientboundEntitySetHeadYawPacket,
        0x43 => clientboundchunkdeltaupdatepacket::ClientboundChunkDeltaUpdatePacket,
        0x44 => clientboundselectadvancementtabpacket::ClientboundSelectAdvancementTabPacket,
        0x45 => clientboundservermetadatapacket::ClientboundServerMetadataPacket,
        0x46 => clientboundoverlaymessagepacket::ClientboundOverlayMessagePacket,
        0x47 => clientboundworldbordercenterchangedpacket::ClientboundWorldBorderCenterChangedPacket,
        0x48 => clientboundworldborderinterpolatesizepacket::ClientboundWorldBorderInterpolateSizePacket,
        0x49 => clientboundworldbordersizechangedpacket::ClientboundWorldBorderSizeChangedPacket,
        0x4a => clientboundworldborderwarningtimechangedpacket::ClientboundWorldBorderWarningTimeChangedPacket,
        0x4b => clientboundworldborderwarningblockschangedpacket::ClientboundWorldBorderWarningBlocksChangedPacket,
        0x4c => clientboundsetcameraentitypacket::ClientboundSetCameraEntityPacket,
        0x4d => clientboundupdateselectedslotpacket::ClientboundUpdateSelectedSlotPacket,
        0x4e => clientboundchunkrenderdistancecenterpacket::ClientboundChunkRenderDistanceCenterPacket,
        0x4f => clientboundchunkloaddistancepacket::ClientboundChunkLoadDistancePacket,
        0x50 => clientboundplayerspawnpositionpacket::ClientboundPlayerSpawnPositionPacket,
        0x51 => clientboundscoreboarddisplaypacket::ClientboundScoreboardDisplayPacket,
        0x52 => clientboundentitytrackerupdatepacket::ClientboundEntityTrackerUpdatePacket,
        0x53 => clientboundentityattachpacket::ClientboundEntityAttachPacket,
        0x54 => clientboundentityvelocityupdatepacket::ClientboundEntityVelocityUpdatePacket,
        0x55 => clientboundentityequipmentupdatepacket::ClientboundEntityEquipmentUpdatePacket,
        0x56 => clientboundexperiencebarupdatepacket::ClientboundExperienceBarUpdatePacket,
        0x57 => clientboundhealthupdatepacket::ClientboundHealthUpdatePacket,
        0x58 => clientboundscoreboardobjectiveupdatepacket::ClientboundScoreboardObjectiveUpdatePacket,
        0x59 => clientboundentitypassengerssetpacket::ClientboundEntityPassengersSetPacket,
        0x5a => clientboundteampacket::ClientboundTeamPacket,
        0x5b => clientboundscoreboardplayerupdatepacket::ClientboundScoreboardPlayerUpdatePacket,
        0x5c => clientboundsimulationdistancepacket::ClientboundSimulationDistancePacket,
        0x5d => clientboundsubtitlepacket::ClientboundSubtitlePacket,
        0x5e => clientboundworldtimeupdatepacket::ClientboundWorldTimeUpdatePacket,
        0x5f => clientboundtitlepacket::ClientboundTitlePacket,
        0x60 => clientboundtitlefadepacket::ClientboundTitleFadePacket,
        0x61 => clientboundplaysoundfromentitypacket::ClientboundPlaySoundFromEntityPacket,
        0x62 => clientboundplaysoundpacket::ClientboundPlaySoundPacket,
        0x63 => clientboundstopsoundpacket::ClientboundStopSoundPacket,
        0x64 => clientboundgamemessagepacket::ClientboundGameMessagePacket,
        0x65 => clientboundplayerlistheaderpacket::ClientboundPlayerListHeaderPacket,
        0x66 => clientboundnbtqueryresponsepacket::ClientboundNbtQueryResponsePacket,
        0x67 => clientbounditempickupanimationpacket::ClientboundItemPickupAnimationPacket,
        0x68 => clientboundentitypositionpacket::ClientboundEntityPositionPacket,
        0x69 => clientboundadvancementupdatepacket::ClientboundAdvancementUpdatePacket,
        0x6a => clientboundentityattributespacket::ClientboundEntityAttributesPacket,
        0x6b => clientboundfeaturespacket::ClientboundFeaturesPacket,
        0x6c => clientboundentitystatuseffectpacket::ClientboundEntityStatusEffectPacket,
        0x6d => clientboundsynchronizerecipespacket::ClientboundSynchronizeRecipesPacket,
        0x6e => clientboundsynchronizetagspacket::ClientboundSynchronizeTagsPacket,
    },
    Serverbound => {
        0x0 => serverboundteleportconfirmpacket::ServerboundTeleportConfirmPacket,
        0x1 => serverboundqueryblocknbtpacket::ServerboundQueryBlockNbtPacket,
        0x2 => serverboundupdatedifficultypacket::ServerboundUpdateDifficultyPacket,
        0x3 => serverboundmessageacknowledgmentpacket::ServerboundMessageAcknowledgmentPacket,
        0x4 => serverboundcommandexecutionpacket::ServerboundCommandExecutionPacket,
        0x5 => serverboundchatmessagepacket::ServerboundChatMessagePacket,
        0x6 => serverboundplayersessionpacket::ServerboundPlayerSessionPacket,
        0x7 => serverboundclientstatuspacket::ServerboundClientStatusPacket,
        0x8 => serverboundclientsettingspacket::ServerboundClientSettingsPacket,
        0x9 => serverboundrequestcommandcompletionspacket::ServerboundRequestCommandCompletionsPacket,
        0xa => serverboundbuttonclickpacket::ServerboundButtonClickPacket,
        0xb => serverboundclickslotpacket::ServerboundClickSlotPacket,
        0xc => serverboundclosehandledscreenpacket::ServerboundCloseHandledScreenPacket,
        0xd => serverboundcustompayloadpacket::ServerboundCustomPayloadPacket,
        0xe => serverboundbookupdatepacket::ServerboundBookUpdatePacket,
        0xf => serverboundqueryentitynbtpacket::ServerboundQueryEntityNbtPacket,
        0x10 => serverboundplayerinteractentitypacket::ServerboundPlayerInteractEntityPacket,
        0x11 => serverboundjigsawgeneratingpacket::ServerboundJigsawGeneratingPacket,
        0x12 => serverboundkeepalivepacket::ServerboundKeepAlivePacket,
        0x13 => serverboundupdatedifficultylockpacket::ServerboundUpdateDifficultyLockPacket,
        0x14 => serverboundplayermovepositionandongroundpacket::ServerboundPlayerMovePositionAndOnGroundPacket,
        0x15 => serverboundplayermovefullpacket::ServerboundPlayerMoveFullPacket,
        0x16 => serverboundplayermovelookandongroundpacket::ServerboundPlayerMoveLookAndOnGroundPacket,
        0x17 => serverboundplayermoveongroundonlypacket::ServerboundPlayerMoveOnGroundOnlyPacket,
        0x18 => serverboundvehiclemovepacket::ServerboundVehicleMovePacket,
        0x19 => serverboundboatpaddlestatepacket::ServerboundBoatPaddleStatePacket,
        0x1a => serverboundpickfrominventorypacket::ServerboundPickFromInventoryPacket,
        0x1b => serverboundcraftrequestpacket::ServerboundCraftRequestPacket,
        0x1c => serverboundupdateplayerabilitiespacket::ServerboundUpdatePlayerAbilitiesPacket,
        0x1d => serverboundplayeractionpacket::ServerboundPlayerActionPacket,
        0x1e => serverboundclientcommandpacket::ServerboundClientCommandPacket,
        0x1f => serverboundplayerinputpacket::ServerboundPlayerInputPacket,
        0x20 => serverboundplaypongpacket::ServerboundPlayPongPacket,
        0x21 => serverboundrecipecategoryoptionspacket::ServerboundRecipeCategoryOptionsPacket,
        0x22 => serverboundrecipebookdatapacket::ServerboundRecipeBookDataPacket,
        0x23 => serverboundrenameitempacket::ServerboundRenameItemPacket,
        0x24 => serverboundresourcepackstatuspacket::ServerboundResourcePackStatusPacket,
        0x25 => serverboundadvancementtabpacket::ServerboundAdvancementTabPacket,
        0x26 => serverboundselectmerchanttradepacket::ServerboundSelectMerchantTradePacket,
        0x27 => serverboundupdatebeaconpacket::ServerboundUpdateBeaconPacket,
        0x28 => serverboundupdateselectedslotpacket::ServerboundUpdateSelectedSlotPacket,
        0x29 => serverboundupdatecommandblockpacket::ServerboundUpdateCommandBlockPacket,
        0x2a => serverboundupdatecommandblockminecartpacket::ServerboundUpdateCommandBlockMinecartPacket,
        0x2b => serverboundcreativeinventoryactionpacket::ServerboundCreativeInventoryActionPacket,
        0x2c => serverboundupdatejigsawpacket::ServerboundUpdateJigsawPacket,
        0x2d => serverboundupdatestructureblockpacket::ServerboundUpdateStructureBlockPacket,
        0x2e => serverboundupdatesignpacket::ServerboundUpdateSignPacket,
        0x2f => serverboundhandswingpacket::ServerboundHandSwingPacket,
        0x30 => serverboundspectatorteleportpacket::ServerboundSpectatorTeleportPacket,
        0x31 => serverboundplayerinteractblockpacket::ServerboundPlayerInteractBlockPacket,
        0x32 => serverboundplayerinteractitempacket::ServerboundPlayerInteractItemPacket,
    },
);
