//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

use crate::common::ResourceKey;

#[derive(Debug, Clone, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct LoginQueryRequestPacket {
    #[frog(var)]
    pub field_0: u32,
    pub field_1: ResourceKey,
}
