//! @generated by `froglight-generator` #ecfea09

use froglight_macros::FrogReadWrite;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, FrogReadWrite)]
pub struct LoginSuccessPacket {
    pub field_0: GameProfile,
    pub field_1: bool,
}
