//! [`Login`](crate::states::Login) state packets for
//! [`V1_21_0`](super::V1_21_0)
//!
//! @generated by `froglight-generator` #cff0bd9
#![allow(missing_docs)]

mod cookie_request;
pub use cookie_request::*;

mod login_query_request;
pub use login_query_request::*;

mod login_success;
pub use login_success::*;

mod login_hello;
pub use login_hello::*;

mod login_compression;
pub use login_compression::*;

mod login_disconnect;
pub use login_disconnect::*;

mod cookie_response;
pub use cookie_response::*;

mod login_query_response;
pub use login_query_response::*;

mod login_key;
pub use login_key::*;

mod enter_configuration;
pub use enter_configuration::*;

froglight_macros::frog_state! {
    Login,
    V1_21_0,
    Clientbound {
        0u32 => CookieRequestPacket,
        1u32 => LoginQueryRequestPacket,
        2u32 => LoginSuccessPacket,
        3u32 => LoginHelloPacket,
        4u32 => LoginCompressionPacket,
        5u32 => LoginDisconnectPacket,
    },
    Serverbound {
        0u32 => CookieResponsePacket,
        1u32 => LoginQueryResponsePacket,
        2u32 => LoginHelloPacket,
        3u32 => LoginKeyPacket,
        4u32 => EnterConfigurationPacket,
    },
}
