//! Packets for [`Handshake`](crate::state::Handshake)
//!
//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @generated by {COMMIT_HASH}

pub use crate::v1_21_4::handshake::*;
