//! Generated block attributes
//!
//! @generated by `froglight-generator` #cd8324b

use froglight_macros::frog_create_attributes;

frog_create_attributes! {
    Age015RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15
    },
    Age01RangeAttribute {
        _0, _1
    },
    Age025RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25
    },
    Age02RangeAttribute {
        _0, _1, _2
    },
    Age03RangeAttribute {
        _0, _1, _2, _3
    },
    Age04RangeAttribute {
        _0, _1, _2, _3, _4
    },
    Age05RangeAttribute {
        _0, _1, _2, _3, _4, _5
    },
    Age07RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7
    },
    AttachedBooleanAttribute(pub bool),
    AttachmentAttribute {
        Ceiling, DoubleWall, Floor, SingleWall
    },
    AxisXYZAttribute {
        X, Y, Z
    },
    AxisXZAttribute {
        X, Z
    },
    BerriesBooleanAttribute(pub bool),
    Bites06RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6
    },
    BloomBooleanAttribute(pub bool),
    BottomBooleanAttribute(pub bool),
    CanSummonBooleanAttribute(pub bool),
    Candles14RangeAttribute {
        _1, _2, _3, _4
    },
    Charges04RangeAttribute {
        _0, _1, _2, _3, _4
    },
    ConditionalBooleanAttribute(pub bool),
    CrackedBooleanAttribute(pub bool),
    CraftingBooleanAttribute(pub bool),
    Delay14RangeAttribute {
        _1, _2, _3, _4
    },
    DisarmedBooleanAttribute(pub bool),
    Distance07RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7
    },
    Distance17RangeAttribute {
        _1, _2, _3, _4, _5, _6, _7
    },
    DownFacingBooleanAttribute(pub bool),
    DragBooleanAttribute(pub bool),
    Dusted03RangeAttribute {
        _0, _1, _2, _3
    },
    EastFacingBooleanAttribute(pub bool),
    EastFacingLowNoneTallAttribute {
        Low, None, Tall
    },
    EastFacingNoneSideUpAttribute {
        None, Side, Up
    },
    Eggs14RangeAttribute {
        _1, _2, _3, _4
    },
    EnabledBooleanAttribute(pub bool),
    ExtendedBooleanAttribute(pub bool),
    EyeBooleanAttribute(pub bool),
    FaceCeilingFloorWallAttribute {
        Ceiling, Floor, Wall
    },
    FacingDownEastNorthSouthUpWestAttribute {
        Down, East, North, South, Up, West
    },
    FacingDownEastNorthSouthWestAttribute {
        Down, East, North, South, West
    },
    FacingEastNorthSouthWestAttribute {
        East, North, South, West
    },
    FlowerAmount14RangeAttribute {
        _1, _2, _3, _4
    },
    HalfBottomTopAttribute {
        Bottom, Top
    },
    HalfLowerUpperAttribute {
        Lower, Upper
    },
    HangingBooleanAttribute(pub bool),
    HasBookBooleanAttribute(pub bool),
    HasBottle0BooleanAttribute(pub bool),
    HasBottle1BooleanAttribute(pub bool),
    HasBottle2BooleanAttribute(pub bool),
    HasRecordBooleanAttribute(pub bool),
    Hatch02RangeAttribute {
        _0, _1, _2
    },
    HingeLeftRightAttribute {
        Left, Right
    },
    HoneyLevel05RangeAttribute {
        _0, _1, _2, _3, _4, _5
    },
    InWallBooleanAttribute(pub bool),
    InstrumentAttribute {
        Banjo, Basedrum, Bass, Bell, Bit, Chime, CowBell, Creeper, CustomHead, Didgeridoo, Dragon, Flute, Guitar, Harp, Hat, IronXylophone, Piglin, Pling, Skeleton, Snare, WitherSkeleton, Xylophone, Zombie
    },
    InvertedBooleanAttribute(pub bool),
    Layers18RangeAttribute {
        _1, _2, _3, _4, _5, _6, _7, _8
    },
    LeavesLargeNoneSmallAttribute {
        Large, None, Small
    },
    Level015RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15
    },
    Level08RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8
    },
    Level13RangeAttribute {
        _1, _2, _3
    },
    LitBooleanAttribute(pub bool),
    LockedBooleanAttribute(pub bool),
    ModeCompareSubtractAttribute {
        Compare, Subtract
    },
    ModeCornerDataLoadSaveAttribute {
        Corner, Data, Load, Save
    },
    Moisture07RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7
    },
    NorthFacingBooleanAttribute(pub bool),
    NorthFacingLowNoneTallAttribute {
        Low, None, Tall
    },
    NorthFacingNoneSideUpAttribute {
        None, Side, Up
    },
    Note024RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24
    },
    OccupiedBooleanAttribute(pub bool),
    OminousBooleanAttribute(pub bool),
    OpenBooleanAttribute(pub bool),
    OrientationAttribute {
        DownEast, DownNorth, DownSouth, DownWest, EastUp, NorthUp, SouthUp, UpEast, UpNorth, UpSouth, UpWest, WestUp
    },
    PartFootHeadAttribute {
        Foot, Head
    },
    PersistentBooleanAttribute(pub bool),
    Pickles14RangeAttribute {
        _1, _2, _3, _4
    },
    Power015RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15
    },
    PoweredBooleanAttribute(pub bool),
    Rotation015RangeAttribute {
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15
    },
    SculkSensorPhaseAttribute {
        Active, Cooldown, Inactive
    },
    ShapeAscendingEastAscendingNorthAscendingSouthAscendingWestEastWestNorthEastNorthSouthNorthWestSouthEastSouthWestAttribute {
        AscendingEast, AscendingNorth, AscendingSouth, AscendingWest, EastWest, NorthEast, NorthSouth, NorthWest, SouthEast, SouthWest
    },
    ShapeAscendingEastAscendingNorthAscendingSouthAscendingWestEastWestNorthSouthAttribute {
        AscendingEast, AscendingNorth, AscendingSouth, AscendingWest, EastWest, NorthSouth
    },
    ShapeInnerLeftInnerRightOuterLeftOuterRightStraightAttribute {
        InnerLeft, InnerRight, OuterLeft, OuterRight, Straight
    },
    ShortBooleanAttribute(pub bool),
    ShriekingBooleanAttribute(pub bool),
    SignalFireBooleanAttribute(pub bool),
    Slot0OccupiedBooleanAttribute(pub bool),
    Slot1OccupiedBooleanAttribute(pub bool),
    Slot2OccupiedBooleanAttribute(pub bool),
    Slot3OccupiedBooleanAttribute(pub bool),
    Slot4OccupiedBooleanAttribute(pub bool),
    Slot5OccupiedBooleanAttribute(pub bool),
    SnowyBooleanAttribute(pub bool),
    SouthFacingBooleanAttribute(pub bool),
    SouthFacingLowNoneTallAttribute {
        Low, None, Tall
    },
    SouthFacingNoneSideUpAttribute {
        None, Side, Up
    },
    Stage01RangeAttribute {
        _0, _1
    },
    ThicknessAttribute {
        Base, Frustum, Middle, Tip, TipMerge
    },
    TiltFullNonePartialUnstableAttribute {
        Full, None, Partial, Unstable
    },
    TrialSpawnerStateAttribute {
        Active, Cooldown, EjectingReward, Inactive, WaitingForPlayers, WaitingForRewardEjection
    },
    TriggeredBooleanAttribute(pub bool),
    TypeBottomDoubleTopAttribute {
        Bottom, Double, Top
    },
    TypeLeftRightSingleAttribute {
        Left, Right, Single
    },
    TypeNormalStickyAttribute {
        Normal, Sticky
    },
    UnstableBooleanAttribute(pub bool),
    UpFacingBooleanAttribute(pub bool),
    VaultStateAttribute {
        Active, Ejecting, Inactive, Unlocking
    },
    VerticalDirectionDownUpAttribute {
        Down, Up
    },
    WaterloggedBooleanAttribute(pub bool),
    WestFacingBooleanAttribute(pub bool),
    WestFacingLowNoneTallAttribute {
        Low, None, Tall
    },
    WestFacingNoneSideUpAttribute {
        None, Side, Up
    },
}
