//! Generated blocks and block attributes
//!
//! @generated by `froglight-generator` #3701f00
#![allow(missing_docs, clippy::module_inception)]

pub mod attributes;
pub mod blocks;

mod v1_21_0;

#[doc(hidden)]
pub(super) fn build(app: &mut bevy_app::App) {
    attributes::build(app);
    blocks::build(app);
}
