//! Generated blocks and block attributes
//!
//! Template: 1.21.0
//!
//! @generated by `froglight-generator` #ba7923a
#![allow(missing_docs)]

pub mod attributes;
pub mod blocks;
mod v1_21_0;

#[doc(hidden)]
#[cfg(feature = "bevy")]
pub(super) fn build(app: &mut bevy_app::App) {
    #[cfg(feature = "reflect")]
    {
        app.register_type::<blocks::Blocks>();
    }

    app.init_resource::<crate::BlockRegistry<froglight_protocol::versions::v1_21_0::V1_21_0>>();
}
