//! [`Status`] state packets for [`1.20.0`]
//!
//! @generated by `froglight-generator #00f1b4b`
#![allow(missing_docs)]

mod queryresponses2cpacket;
pub use queryresponses2cpacket::*;

mod querypongs2cpacket;
pub use querypongs2cpacket::*;

mod queryrequestc2spacket;
pub use queryrequestc2spacket::*;

mod querypingc2spacket;
pub use querypingc2spacket::*;
