//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use derive_more::{Deref, DerefMut};
use froglight_common::identifier::Identifier;

#[derive(Debug, Default, Clone, PartialEq, Eq, Hash, Deref, DerefMut)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Default, Clone, PartialEq, Hash))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct FeaturesS2CPacket {
    pub features: Vec<Identifier>,
}
