//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

use bevy_platform::collections::HashMap;
#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_common::identifier::Identifier;
use froglight_nbt::nbt::NbtCompound;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf))]
pub struct DynamicRegistriesS2CPacket {
    pub registry: Identifier,
    pub entries: HashMap<Identifier, Option<NbtCompound>>,
}
