//! This file is auto-generated. Disable this by adding an `@manual` tag.
//!
//! @manual @generated by {COMMIT_HASH}

#[cfg(feature = "bevy")]
use bevy_reflect::prelude::*;
use froglight_common::identifier::Identifier;

use crate::common::UnsizedVec;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "bevy", derive(Reflect), reflect(Debug, Clone, PartialEq))]
#[cfg_attr(feature = "io", derive(froglight_macros::FrogBuf), frog(version))]
pub struct DynamicRegistriesS2CPacket {
    pub registry: Identifier,
    pub entries: UnsizedVec<u8>,
    // pub entries: HashMap<Identifier, Option<NbtCompound>>,
}
