//! [`Login`] state packets for [`1.20.0`]
//!
//! @generated by `froglight-generator #00f1b4b`
#![allow(missing_docs)]

use froglight_macros::frog_state;

mod logindisconnects2cpacket;
pub use logindisconnects2cpacket::*;

mod loginhellos2cpacket;
pub use loginhellos2cpacket::*;

mod loginsuccesss2cpacket;
pub use loginsuccesss2cpacket::*;

mod logincompressions2cpacket;
pub use logincompressions2cpacket::*;

mod loginqueryrequests2cpacket;
pub use loginqueryrequests2cpacket::*;

mod loginhelloc2spacket;
pub use loginhelloc2spacket::*;

mod loginkeyc2spacket;
pub use loginkeyc2spacket::*;

mod loginqueryresponsec2spacket;
pub use loginqueryresponsec2spacket::*;

frog_state! {
    Login,
    V1_20_0,
    Clientbound {
        0x00 => LoginDisconnectS2CPacket,
        0x01 => LoginHelloS2CPacket,
        0x02 => LoginSuccessS2CPacket,
        0x03 => LoginCompressionS2CPacket,
        0x04 => LoginQueryRequestS2CPacket,
    },
    Serverbound {
        0x00 => LoginHelloC2SPacket,
        0x01 => LoginKeyC2SPacket,
        0x02 => LoginQueryResponseC2SPacket,
    },
}
